#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG

//#define DEAL_WITH_HORIZON_EFFECT

//#define RANDOM_BEST_MOVE

#define HASH_MAP_ENABLE

#ifdef DEBUG
#define DONOT_PLAY_SOUND
#define DEBUG_AB_TREE
#endif

#ifndef DEBUG
//#define AB_RANDOM_SORT_CHILDREN
#endif

//#define DONOT_PLAY_SOUND

#ifdef DEBUG
#define GAME_PLACING_FIXED_DEPTH  4
#endif

#ifdef DEBUG
#define GAME_MOVING_FIXED_DEPTH  3
#else // DEBUG
#ifdef DEAL_WITH_HORIZON_EFFECT
#define GAME_MOVING_FIXED_DEPTH 10
#else // DEAL_WITH_HORIZON_EFFECT
#define GAME_MOVING_FIXED_DEPTH  10
#endif // DEAL_WITH_HORIZON_EFFECT
#endif // DEBUG

#ifndef DEBUG
#define GAME_PLACING_DYNAMIC_DEPTH
#endif

#ifdef DEBUG
#define DRAW_SEAT_NUMBER
#endif

//#define IDS_SUPPORT

#define SAVE_CHESSBOOK_WHEN_ACTION_NEW_TRIGGERED

// #define DONOT_PLAY_WIN_SOUND

// 摆棋阶段在叉下面显示被吃的子
//#define GAME_PLACING_SHOW_CAPTURED_PIECES

// 启动时窗口最大化
//#define SHOW_MAXIMIZED_ON_LOAD

#endif // CONFIG_H