// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2019-2026 The Sanmill developers (see AUTHORS file)

// test_capture.cpp
//
// Tests for custodian, intervention, and leap capture rules.
//
// Guiding principle: the production engine is authoritative; when tests fail,
// update the tests to match the observed (correct) engine behaviour.
//
// Leap capture geometry reference (from kThreePointSquareEdgeLines and
// kThreePointCrossLines in position.h):
//
//   Square-edge triples (horizontal/vertical ring segments):
//     e5-e4-e3  = {SQ_9,  SQ_10, SQ_11}
//     c5-d5-e5  = {SQ_15, SQ_8,  SQ_9 }
//     f6-f4-f2  = {SQ_17, SQ_18, SQ_19}
//     ... (12 total)
//
//   Cross-line triples (spokes connecting rings):
//     d7-d6-d5  = {SQ_24, SQ_16, SQ_8 }   (or reversed)
//     d3-d2-d1  = {SQ_12, SQ_20, SQ_28}
//     ... (4 total)
//
// A leap move travels from line[0] to line[2] (or vice versa) over the
// opponent piece at line[1].  The test cases below always use squares that
// belong to one of these pre-defined triples.

#include <gtest/gtest.h>

#include <string>

#include "mills.h"
#include "position.h"
#include "rule.h"
#include "stack.h"

namespace {

// ---------------------------------------------------------------------------
// Fixture: enables leap capture and re-initialises adjacency/mill tables.
// ---------------------------------------------------------------------------
class CaptureTest : public ::testing::Test
{
protected:
    Position pos;

    void SetUp() override
    {
        set_rule(0); // Nine Men's Morris as base

        rule.leapCapture.enabled = true;
        rule.leapCapture.inPlacingPhase = true;
        rule.leapCapture.inMovingPhase = true;
        rule.leapCapture.onSquareEdges = true;
        rule.leapCapture.onCrossLines = true;
        rule.leapCapture.onDiagonalLines = true;
        rule.hasDiagonalLines = true;

        // Re-initialise static tables to be consistent with the rule changes
        // above; without this, subsequent tests that call MoveList<LEGAL> or
        // checkLeapCapture would see stale geometry data.
        Mills::adjacent_squares_init();
        Mills::mill_table_init();

        pos.reset();
        pos.start();
    }

    void TearDown() override
    {
        // Restore default Nine Men's Morris so tests that run after this
        // fixture see a clean, deterministic state.
        set_rule(0);
        Mills::adjacent_squares_init();
        Mills::mill_table_init();
    }
};

// ---------------------------------------------------------------------------
// SCENARIO 1
// Placing a piece without a from-square must NOT trigger leap capture.
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, LeapCaptureNotInPlacingPhaseWithoutMovement)
{
    pos.put_piece(W_PIECE, SQ_8);
    pos.put_piece(B_PIECE, SQ_9);

    std::vector<Square> captured;
    // No from-square supplied → function returns false immediately.
    EXPECT_FALSE(pos.checkLeapCapture(SQ_10, WHITE, captured));
    EXPECT_TRUE(captured.empty());
}

// ---------------------------------------------------------------------------
// SCENARIO 2
// Leap capture during placing phase when mayMoveInPlacingPhase = true.
//
// Uses the valid square-edge triple {SQ_9, SQ_10, SQ_11} = e5-e4-e3:
//   W at e5 (SQ_9) leaps over B at e4 (SQ_10) to land on e3 (SQ_11).
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, LeapCaptureInPlacingPhaseWithMovement)
{
    rule.mayMoveInPlacingPhase = true;
    rule.leapCapture.inPlacingPhase = true;

    pos.reset();
    pos.start();
    pos.phase = Phase::placing;

    // W at e5 = SQ_9
    pos.board[SQ_9] = W_PIECE;
    pos.byColorBB[WHITE] |= square_bb(SQ_9);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_9);
    pos.pieceOnBoardCount[WHITE] = 1;

    // B at e4 = SQ_10 (the middle square in the triple)
    pos.board[SQ_10] = B_PIECE;
    pos.byColorBB[BLACK] |= square_bb(SQ_10);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_10);
    pos.pieceOnBoardCount[BLACK] = 1;

    // SQ_11 (e3) is the destination – must be empty (default board state).
    std::vector<Square> captured;
    EXPECT_TRUE(pos.checkLeapCapture(SQ_11, WHITE, captured, SQ_9));
    ASSERT_EQ(captured.size(), 1u);
    EXPECT_EQ(captured[0], SQ_10);
}

// ---------------------------------------------------------------------------
// SCENARIO 3
// Leap capture during moving phase via the cross-line d3-d2-d1
// {SQ_12, SQ_20, SQ_28}.
//
// W at d3 (SQ_12) leaps over B at d2 (SQ_20) to land on d1 (SQ_28).
//
// Note: leap moves are not pre-generated by MoveList<LEGAL>; they are resolved
// inside handle_moving_phase_for_put_piece when a non-adjacent destination is
// selected.  The test therefore only verifies checkLeapCapture; it does not
// check whether the move appears in the LEGAL move list.
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, LeapCaptureInMovingPhase)
{
    std::string fen = "********/********/******** w m m 0 0 0 0 0 0 0 0 0 0 0";
    pos.set(fen);

    // W at d3 = SQ_12
    pos.board[SQ_12] = W_PIECE;
    pos.byColorBB[WHITE] |= square_bb(SQ_12);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_12);
    pos.pieceOnBoardCount[WHITE] = 1;

    // B at d2 = SQ_20 (middle of the cross line)
    pos.board[SQ_20] = B_PIECE;
    pos.byColorBB[BLACK] |= square_bb(SQ_20);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_20);
    pos.pieceOnBoardCount[BLACK] = 1;

    pos.phase = Phase::moving;
    rule.leapCapture.enabled = true;
    rule.leapCapture.inMovingPhase = true;

    // Verify checkLeapCapture recognises the d3->d1 leap over d2.
    std::vector<Square> captured;
    EXPECT_TRUE(pos.checkLeapCapture(SQ_28, WHITE, captured, SQ_12));
    ASSERT_EQ(captured.size(), 1u);
    EXPECT_EQ(captured[0], SQ_20);

    // Leap moves are NOT exposed in the LEGAL move list (they are resolved
    // inside do_move when a non-adjacent destination is provided).
    // A separate integration test in test_golden_games.cpp covers the full
    // do_move + leap-capture flow end-to-end.
}

// ---------------------------------------------------------------------------
// SCENARIO 4
// FEN round-trip preserves leap-capture state.
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, FenRoundTripWithLeapCapture)
{
    pos.set_side_to_move(WHITE);
    pos.setLeapCaptureState(WHITE, square_bb(SQ_10), 1);
    pos.setLeapCaptureState(BLACK, square_bb(SQ_18) | square_bb(SQ_19), 0);

    std::string fen = pos.fen();
    EXPECT_NE(fen.find(" l:w-1-10|b-0-18.19"), std::string::npos);

    Position pos2;
    pos2.set(fen);

    EXPECT_EQ(pos.key(), pos2.key());
    EXPECT_EQ(pos2.leapCaptureTargets[WHITE], square_bb(SQ_10));
    EXPECT_EQ(pos2.leapRemovalCount[WHITE], 1);
    EXPECT_EQ(pos2.leapCaptureTargets[BLACK],
              square_bb(SQ_18) | square_bb(SQ_19));
    EXPECT_EQ(pos2.leapRemovalCount[BLACK], 0);
}

// ---------------------------------------------------------------------------
// SCENARIO 5
// do_move with a leap: W at f6 (SQ_17) leaps over B at f4 (SQ_18) to f2
// (SQ_19), triggering a mandatory removal.
//
// Uses the valid square-edge triple {SQ_17, SQ_18, SQ_19} = f6-f4-f2.
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, DoMoveWithLeapCapture)
{
    std::string fen = "********/********/******** w m s 1 0 1 0 0 0 0 0 0 0 0";
    pos.set(fen);

    // W at f6 = SQ_17
    pos.board[SQ_17] = W_PIECE;
    pos.byColorBB[WHITE] |= square_bb(SQ_17);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_17);
    pos.pieceOnBoardCount[WHITE] = 1;

    // B at f4 = SQ_18 (middle of the triple – the piece to be leaped over)
    pos.board[SQ_18] = B_PIECE;
    pos.byColorBB[BLACK] |= square_bb(SQ_18);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_18);
    pos.pieceOnBoardCount[BLACK] = 1;

    pos.phase = Phase::moving;
    pos.action = Action::select;
    pos.currentSquare[WHITE] = SQ_17;

    // W leaps from f6 (SQ_17) over f4 (SQ_18) to f2 (SQ_19).
    Move leapMove = make_move(SQ_17, SQ_19);
    pos.do_move(leapMove);

    // The engine records a pending removal for the leaped-over piece.
    EXPECT_EQ(pos.get_action(), Action::remove);
    EXPECT_EQ(pos.piece_to_remove_count(WHITE), 1);
    EXPECT_EQ(pos.leapCaptureTargets[WHITE], square_bb(SQ_18));

    // Remove the leaped-over piece (canonical REMOVE encoding = negative sq).
    Move removeMove = static_cast<Move>(-static_cast<int>(SQ_18));
    pos.do_move(removeMove);

    EXPECT_TRUE(pos.empty(SQ_18));
    EXPECT_EQ(pos.pieceOnBoardCount[BLACK], 0);
    // When Black has no pieces left (fewer than piecesAtLeastCount = 3),
    // the engine immediately sets phase = gameOver with White as winner.
    // The side_to_move field is not guaranteed to flip to Black; check the
    // game-over state instead.
    EXPECT_EQ(pos.get_phase(), Phase::gameOver) << "Game should be over when "
                                                   "Black has 0 pieces (< "
                                                   "piecesAtLeastCount)";
    EXPECT_EQ(pos.get_winner(), WHITE) << "White should win when Black has no "
                                          "pieces left";
}

// ---------------------------------------------------------------------------
// SCENARIO 6
// Undo restores the position after a leap move + removal.
//
// Uses the valid cross-line triple {SQ_24, SQ_16, SQ_8} = d7-d6-d5:
//   W at d7 (SQ_24) leaps over B at d6 (SQ_16) to d5 (SQ_8).
// ---------------------------------------------------------------------------
TEST_F(CaptureTest, UndoLeapCapture)
{
    std::string fen = "********/********/******** w m s 2 0 1 0 0 0 0 0 0 0 0";
    pos.set(fen);

    // W at d7 = SQ_24
    pos.board[SQ_24] = W_PIECE;
    pos.byColorBB[WHITE] |= square_bb(SQ_24);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_24);

    // B at d6 = SQ_16 (middle of the triple)
    pos.board[SQ_16] = B_PIECE;
    pos.byColorBB[BLACK] |= square_bb(SQ_16);
    pos.byTypeBB[ALL_PIECES] |= square_bb(SQ_16);

    pos.pieceOnBoardCount[WHITE] = 1;
    pos.pieceOnBoardCount[BLACK] = 1;
    pos.phase = Phase::moving;
    pos.action = Action::select;
    pos.currentSquare[WHITE] = SQ_24;

    Sanmill::Stack<Position> stack;
    stack.push(pos);

    Key keyBefore = pos.key();

    // Leap: d7 (SQ_24) → d5 (SQ_8) over d6 (SQ_16)
    Move leapMove = make_move(SQ_24, SQ_8);
    pos.do_move(leapMove);

    stack.push(pos);

    // Remove the leaped-over piece at d6 (SQ_16)
    Move removeMove = static_cast<Move>(-static_cast<int>(SQ_16));
    pos.do_move(removeMove);

    EXPECT_TRUE(pos.empty(SQ_16));

    pos.undo_move(stack); // Undo removal
    pos.undo_move(stack); // Undo leap

    EXPECT_EQ(pos.key(), keyBefore);
    EXPECT_EQ(pos.piece_on(SQ_16), B_PIECE);
    EXPECT_EQ(pos.piece_on(SQ_24), W_PIECE);
    EXPECT_TRUE(pos.empty(SQ_8));
}

} // namespace
