include: package:lint/analysis_options.yaml


linter:
  rules:
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    avoid_escaping_inner_quotes: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    # generated code
    - lib/generated/**
    - lib/l10n/**
