targets:
  $default:
    builders:
      copy_with_extension_gen|copy_with_extension_gen:
        enabled: true
        generate_for:
          - "**/models/**.dart"
          - "**/model/**.dart"
      json_serializable|json_serializable:
        options:
          field_rename: pascal
        enabled: true
        generate_for:
          - "**/models/**.dart"
          - "**/model/**.dart"
      hive_ce_generator|hive_type_adapter_generator:
        enabled: true
        generate_for:
          - "**/models/**.dart"
          - "**/model/**.dart"
      hive_ce_generator|hive_registrar_generator:
        enabled: true
        options:
          ignore_for_file:
            - prefer_relative_imports
            - document_ignores
            - public_member_api_docs
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - prefer_relative_imports
            - document_ignores
            - public_member_api_docs