// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/kernel.dart';
import 'api/mill_kernel.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 506360117;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_sanmill',
        ioDirectory: '../../../crates/tgf-frb/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  TopologyBlob crateApiSimpleKernelTopology();

  Future<MillEngineConfig> crateApiSimpleMillEngineConfigDefault();

  void crateApiSimpleMillPerfectDbDeinit();

  bool crateApiSimpleMillPerfectDbInit({required String path});

  Future<MillSearchAlgorithm> crateApiSimpleMillSearchAlgorithmDefault();

  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove();

  MillVariantOptions crateApiSimpleNativeMillDefaultVariantOptions();

  int crateApiSimpleNativeMillInitialLegalCount();

  int crateApiSimpleNativeMillInitialLegalCountForVariant({
    required MillVariantOptions variant,
  });

  int crateApiSimpleNativeMillMctsBestToNode({
    required BigInt seed,
    required int iterationsPerMove,
  });

  int crateApiSimpleNativeMillMillSequenceRemoveCount();

  int crateApiSimpleNativeMillMovingMillRemoveCount();

  int crateApiSimpleNativeMillPvsDepthOneBestToNode();

  int crateApiSimpleNativeMillRandomBestToNode({required BigInt seed});

  int crateApiSimpleNativeMillRemovalBelowThreeWinner();

  int crateApiSimpleNativeMillSearchDepthOneBestToNode();

  Stream<EngineEvent> crateApiSimpleNativeMillSearchEvents({
    required int depth,
  });

  bool crateApiSimpleNativeMillSearchStop();

  bool crateApiSimpleNativeMillSearchZeroTimeLimitAborts();

  TopologyBlob crateApiSimpleNativeMillTopology();

  int crateApiSimpleNativeOthelloInitialLegalCount();

  int crateApiSimpleNativeOthelloSearchDepthOneBestToNode();

  String crateApiSimpleTgfHelloWorld();

  TgfSnapshot crateApiKernelTgfKernelApply({
    required int handle,
    required TgfAction action,
  });

  TgfSnapshot crateApiKernelTgfKernelApplyUnchecked({
    required int handle,
    required TgfAction action,
  });

  int crateApiKernelTgfKernelCreate({required String gameId});

  int crateApiMillKernelTgfKernelCreateMill({
    required MillVariantOptions variant,
  });

  void crateApiKernelTgfKernelDispose({required int handle});

  String crateApiMillKernelTgfKernelExportFen({required int handle});

  String crateApiKernelTgfKernelGameId({required int handle});

  bool crateApiKernelTgfKernelIsTerminal({required int handle});

  List<TgfAction> crateApiKernelTgfKernelLegalActions({required int handle});

  Stream<EngineEvent> crateApiMillKernelTgfKernelMillSearchEvents({
    required int handle,
    required int depth,
  });

  Stream<EngineEvent> crateApiMillKernelTgfKernelMillSearchEventsWithConfig({
    required int handle,
    required MillEngineConfig config,
  });

  TgfOutcome crateApiKernelTgfKernelOutcome({required int handle});

  PlayerInfoBlob crateApiSimpleTgfKernelPlayerInfo({required int handle});

  TgfSnapshot crateApiKernelTgfKernelRedo({required int handle});

  int crateApiKernelTgfKernelRedoDepth({required int handle});

  TgfSnapshot crateApiMillKernelTgfKernelSetFromFen({
    required int handle,
    required String fen,
  });

  TgfSnapshot crateApiMillKernelTgfKernelSetupClear({required int handle});

  TgfSnapshot crateApiMillKernelTgfKernelSetupFinish({required int handle});

  TgfSnapshot crateApiMillKernelTgfKernelSetupSetPiece({
    required int handle,
    required int node,
    required int owner,
  });

  TgfSnapshot crateApiMillKernelTgfKernelSetupSetSide({
    required int handle,
    required int side,
  });

  TgfSnapshot crateApiKernelTgfKernelSnapshot({required int handle});

  TopologyBlob crateApiSimpleTgfKernelTopology({required int handle});

  TgfSnapshot crateApiKernelTgfKernelUndo({required int handle});

  int crateApiKernelTgfKernelUndoDepth({required int handle});

  String crateApiSimpleTgfVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  TopologyBlob crateApiSimpleKernelTopology() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_topology_blob,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleKernelTopologyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleKernelTopologyConstMeta =>
      const TaskConstMeta(debugName: "kernel_topology", argNames: []);

  @override
  Future<MillEngineConfig> crateApiSimpleMillEngineConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mill_engine_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMillEngineConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMillEngineConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "mill_engine_config_default",
        argNames: [],
      );

  @override
  void crateApiSimpleMillPerfectDbDeinit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMillPerfectDbDeinitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMillPerfectDbDeinitConstMeta =>
      const TaskConstMeta(debugName: "mill_perfect_db_deinit", argNames: []);

  @override
  bool crateApiSimpleMillPerfectDbInit({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMillPerfectDbInitConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMillPerfectDbInitConstMeta =>
      const TaskConstMeta(
        debugName: "mill_perfect_db_init",
        argNames: ["path"],
      );

  @override
  Future<MillSearchAlgorithm> crateApiSimpleMillSearchAlgorithmDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mill_search_algorithm,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMillSearchAlgorithmDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMillSearchAlgorithmDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "mill_search_algorithm_default",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_apply_first_place_side_to_move",
        argNames: [],
      );

  @override
  MillVariantOptions crateApiSimpleNativeMillDefaultVariantOptions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mill_variant_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillDefaultVariantOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillDefaultVariantOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_default_variant_options",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillInitialLegalCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillInitialLegalCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillInitialLegalCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_initial_legal_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillInitialLegalCountForVariant({
    required MillVariantOptions variant,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mill_variant_options(variant, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleNativeMillInitialLegalCountForVariantConstMeta,
        argValues: [variant],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillInitialLegalCountForVariantConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_initial_legal_count_for_variant",
        argNames: ["variant"],
      );

  @override
  int crateApiSimpleNativeMillMctsBestToNode({
    required BigInt seed,
    required int iterationsPerMove,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seed, serializer);
          sse_encode_u_32(iterationsPerMove, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMctsBestToNodeConstMeta,
        argValues: [seed, iterationsPerMove],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMctsBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_mcts_best_to_node",
        argNames: ["seed", "iterationsPerMove"],
      );

  @override
  int crateApiSimpleNativeMillMillSequenceRemoveCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_mill_sequence_remove_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillMovingMillRemoveCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMovingMillRemoveCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMovingMillRemoveCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_moving_mill_remove_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillPvsDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillPvsDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillPvsDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_pvs_depth_one_best_to_node",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillRandomBestToNode({required BigInt seed}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillRandomBestToNodeConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillRandomBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_random_best_to_node",
        argNames: ["seed"],
      );

  @override
  int crateApiSimpleNativeMillRemovalBelowThreeWinner() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillRemovalBelowThreeWinnerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillRemovalBelowThreeWinnerConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_removal_below_three_winner",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillSearchDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillSearchDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_depth_one_best_to_node",
        argNames: [],
      );

  @override
  Stream<EngineEvent> crateApiSimpleNativeMillSearchEvents({
    required int depth,
  }) {
    final sink = RustStreamSink<EngineEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_32(depth, serializer);
            sse_encode_StreamSink_engine_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleNativeMillSearchEventsConstMeta,
          argValues: [depth, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleNativeMillSearchEventsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_events",
        argNames: ["depth", "sink"],
      );

  @override
  bool crateApiSimpleNativeMillSearchStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillSearchStopConstMeta =>
      const TaskConstMeta(debugName: "native_mill_search_stop", argNames: []);

  @override
  bool crateApiSimpleNativeMillSearchZeroTimeLimitAborts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchZeroTimeLimitAbortsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillSearchZeroTimeLimitAbortsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_zero_time_limit_aborts",
        argNames: [],
      );

  @override
  TopologyBlob crateApiSimpleNativeMillTopology() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_topology_blob,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillTopologyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillTopologyConstMeta =>
      const TaskConstMeta(debugName: "native_mill_topology", argNames: []);

  @override
  int crateApiSimpleNativeOthelloInitialLegalCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeOthelloInitialLegalCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeOthelloInitialLegalCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_othello_initial_legal_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeOthelloSearchDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleNativeOthelloSearchDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeOthelloSearchDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_othello_search_depth_one_best_to_node",
        argNames: [],
      );

  @override
  String crateApiSimpleTgfHelloWorld() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfHelloWorldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "tgf_hello_world", argNames: []);

  @override
  TgfSnapshot crateApiKernelTgfKernelApply({
    required int handle,
    required TgfAction action,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_box_autoadd_tgf_action(action, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelApplyConstMeta,
        argValues: [handle, action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelApplyConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_apply",
        argNames: ["handle", "action"],
      );

  @override
  TgfSnapshot crateApiKernelTgfKernelApplyUnchecked({
    required int handle,
    required TgfAction action,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_box_autoadd_tgf_action(action, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelApplyUncheckedConstMeta,
        argValues: [handle, action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelApplyUncheckedConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_apply_unchecked",
        argNames: ["handle", "action"],
      );

  @override
  int crateApiKernelTgfKernelCreate({required String gameId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(gameId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelCreateConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelCreateConstMeta =>
      const TaskConstMeta(debugName: "tgf_kernel_create", argNames: ["gameId"]);

  @override
  int crateApiMillKernelTgfKernelCreateMill({
    required MillVariantOptions variant,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mill_variant_options(variant, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelCreateMillConstMeta,
        argValues: [variant],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelCreateMillConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_create_mill",
        argNames: ["variant"],
      );

  @override
  void crateApiKernelTgfKernelDispose({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKernelTgfKernelDisposeConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelDisposeConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_dispose",
        argNames: ["handle"],
      );

  @override
  String crateApiMillKernelTgfKernelExportFen({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelExportFenConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelExportFenConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_export_fen",
        argNames: ["handle"],
      );

  @override
  String crateApiKernelTgfKernelGameId({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelGameIdConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelGameIdConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_game_id",
        argNames: ["handle"],
      );

  @override
  bool crateApiKernelTgfKernelIsTerminal({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelIsTerminalConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelIsTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_is_terminal",
        argNames: ["handle"],
      );

  @override
  List<TgfAction> crateApiKernelTgfKernelLegalActions({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tgf_action,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelLegalActionsConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelLegalActionsConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_legal_actions",
        argNames: ["handle"],
      );

  @override
  Stream<EngineEvent> crateApiMillKernelTgfKernelMillSearchEvents({
    required int handle,
    required int depth,
  }) {
    final sink = RustStreamSink<EngineEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(handle, serializer);
            sse_encode_i_32(depth, serializer);
            sse_encode_StreamSink_engine_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 34,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMillKernelTgfKernelMillSearchEventsConstMeta,
          argValues: [handle, depth, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelMillSearchEventsConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_mill_search_events",
        argNames: ["handle", "depth", "sink"],
      );

  @override
  Stream<EngineEvent> crateApiMillKernelTgfKernelMillSearchEventsWithConfig({
    required int handle,
    required MillEngineConfig config,
  }) {
    final sink = RustStreamSink<EngineEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(handle, serializer);
            sse_encode_box_autoadd_mill_engine_config(config, serializer);
            sse_encode_StreamSink_engine_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 35,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiMillKernelTgfKernelMillSearchEventsWithConfigConstMeta,
          argValues: [handle, config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiMillKernelTgfKernelMillSearchEventsWithConfigConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_mill_search_events_with_config",
        argNames: ["handle", "config", "sink"],
      );

  @override
  TgfOutcome crateApiKernelTgfKernelOutcome({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_outcome,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelOutcomeConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelOutcomeConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_outcome",
        argNames: ["handle"],
      );

  @override
  PlayerInfoBlob crateApiSimpleTgfKernelPlayerInfo({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_info_blob,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTgfKernelPlayerInfoConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfKernelPlayerInfoConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_player_info",
        argNames: ["handle"],
      );

  @override
  TgfSnapshot crateApiKernelTgfKernelRedo({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelRedoConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelRedoConstMeta =>
      const TaskConstMeta(debugName: "tgf_kernel_redo", argNames: ["handle"]);

  @override
  int crateApiKernelTgfKernelRedoDepth({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelRedoDepthConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelRedoDepthConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_redo_depth",
        argNames: ["handle"],
      );

  @override
  TgfSnapshot crateApiMillKernelTgfKernelSetFromFen({
    required int handle,
    required String fen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_String(fen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelSetFromFenConstMeta,
        argValues: [handle, fen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelSetFromFenConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_set_from_fen",
        argNames: ["handle", "fen"],
      );

  @override
  TgfSnapshot crateApiMillKernelTgfKernelSetupClear({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelSetupClearConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelSetupClearConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_setup_clear",
        argNames: ["handle"],
      );

  @override
  TgfSnapshot crateApiMillKernelTgfKernelSetupFinish({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelSetupFinishConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelSetupFinishConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_setup_finish",
        argNames: ["handle"],
      );

  @override
  TgfSnapshot crateApiMillKernelTgfKernelSetupSetPiece({
    required int handle,
    required int node,
    required int owner,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_i_32(node, serializer);
          sse_encode_i_32(owner, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelSetupSetPieceConstMeta,
        argValues: [handle, node, owner],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelSetupSetPieceConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_setup_set_piece",
        argNames: ["handle", "node", "owner"],
      );

  @override
  TgfSnapshot crateApiMillKernelTgfKernelSetupSetSide({
    required int handle,
    required int side,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_i_32(side, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMillKernelTgfKernelSetupSetSideConstMeta,
        argValues: [handle, side],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMillKernelTgfKernelSetupSetSideConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_setup_set_side",
        argNames: ["handle", "side"],
      );

  @override
  TgfSnapshot crateApiKernelTgfKernelSnapshot({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelSnapshotConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_snapshot",
        argNames: ["handle"],
      );

  @override
  TopologyBlob crateApiSimpleTgfKernelTopology({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_topology_blob,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTgfKernelTopologyConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfKernelTopologyConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_topology",
        argNames: ["handle"],
      );

  @override
  TgfSnapshot crateApiKernelTgfKernelUndo({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tgf_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelUndoConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelUndoConstMeta =>
      const TaskConstMeta(debugName: "tgf_kernel_undo", argNames: ["handle"]);

  @override
  int crateApiKernelTgfKernelUndoDepth({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKernelTgfKernelUndoDepthConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelTgfKernelUndoDepthConstMeta =>
      const TaskConstMeta(
        debugName: "tgf_kernel_undo_depth",
        argNames: ["handle"],
      );

  @override
  String crateApiSimpleTgfVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfVersionConstMeta =>
      const TaskConstMeta(debugName: "tgf_version", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<EngineEvent> dco_decode_StreamSink_engine_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MillEngineConfig dco_decode_box_autoadd_mill_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mill_engine_config(raw);
  }

  @protected
  MillVariantOptions dco_decode_box_autoadd_mill_variant_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mill_variant_options(raw);
  }

  @protected
  TgfAction dco_decode_box_autoadd_tgf_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tgf_action(raw);
  }

  @protected
  CaptureRuleConfig dco_decode_capture_rule_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CaptureRuleConfig(
      enabled: dco_decode_bool(arr[0]),
      onSquareEdges: dco_decode_bool(arr[1]),
      onCrossLines: dco_decode_bool(arr[2]),
      onDiagonalLines: dco_decode_bool(arr[3]),
      inPlacingPhase: dco_decode_bool(arr[4]),
      inMovingPhase: dco_decode_bool(arr[5]),
      onlyAvailableWhenOwnPiecesLeq3: dco_decode_bool(arr[6]),
    );
  }

  @protected
  EngineEvent dco_decode_engine_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EngineEvent(
      kind: dco_decode_String(arr[0]),
      depth: dco_decode_i_32(arr[1]),
      score: dco_decode_i_32(arr[2]),
      nodes: dco_decode_u_64(arr[3]),
      toNode: dco_decode_i_32(arr[4]),
      reason: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Uint16List> dco_decode_list_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_u_16_strict)
        .toList();
  }

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TgfAction> dco_decode_list_tgf_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tgf_action).toList();
  }

  @protected
  List<TopologyEdge> dco_decode_list_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_edge).toList();
  }

  @protected
  List<TopologyPoint> dco_decode_list_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_point).toList();
  }

  @protected
  MillBoardFullAction dco_decode_mill_board_full_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MillBoardFullAction.values[raw as int];
  }

  @protected
  MillEngineConfig dco_decode_mill_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MillEngineConfig(
      algorithm: dco_decode_mill_search_algorithm(arr[0]),
      depth: dco_decode_i_32(arr[1]),
      moveTimeMs: dco_decode_u_32(arr[2]),
      aiIsLazy: dco_decode_bool(arr[3]),
      lastBestValue: dco_decode_i_32(arr[4]),
      skillLevel: dco_decode_u_8(arr[5]),
      usePerfectDatabase: dco_decode_bool(arr[6]),
    );
  }

  @protected
  MillFormationActionInPlacingPhase
  dco_decode_mill_formation_action_in_placing_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MillFormationActionInPlacingPhase.values[raw as int];
  }

  @protected
  MillSearchAlgorithm dco_decode_mill_search_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MillSearchAlgorithm.values[raw as int];
  }

  @protected
  MillVariantOptions dco_decode_mill_variant_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 23)
      throw Exception('unexpected arr length: expect 23 but see ${arr.length}');
    return MillVariantOptions(
      pieceCount: dco_decode_u_8(arr[0]),
      flyPieceCount: dco_decode_u_8(arr[1]),
      piecesAtLeastCount: dco_decode_u_8(arr[2]),
      mayFly: dco_decode_bool(arr[3]),
      hasDiagonalLines: dco_decode_bool(arr[4]),
      millFormationActionInPlacingPhase:
          dco_decode_mill_formation_action_in_placing_phase(arr[5]),
      mayRemoveFromMillsAlways: dco_decode_bool(arr[6]),
      mayRemoveMultiple: dco_decode_bool(arr[7]),
      nMoveRule: dco_decode_u_32(arr[8]),
      endgameNMoveRule: dco_decode_u_32(arr[9]),
      mayMoveInPlacingPhase: dco_decode_bool(arr[10]),
      isDefenderMoveFirst: dco_decode_bool(arr[11]),
      restrictRepeatedMillsFormation: dco_decode_bool(arr[12]),
      oneTimeUseMill: dco_decode_bool(arr[13]),
      stopPlacingWhenTwoEmptySquares: dco_decode_bool(arr[14]),
      boardFullAction: dco_decode_mill_board_full_action(arr[15]),
      threefoldRepetitionRule: dco_decode_bool(arr[16]),
      custodianCapture: dco_decode_capture_rule_config(arr[17]),
      interventionCapture: dco_decode_capture_rule_config(arr[18]),
      leapCapture: dco_decode_capture_rule_config(arr[19]),
      stalemateAction: dco_decode_stalemate_action(arr[20]),
      considerMobility: dco_decode_bool(arr[21]),
      focusOnBlockingPaths: dco_decode_bool(arr[22]),
    );
  }

  @protected
  PlayerInfoBlob dco_decode_player_info_blob(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PlayerInfoBlob(
      playerCount: dco_decode_u_8(arr[0]),
      teamOf: dco_decode_list_prim_u_8_strict(arr[1]),
      turnOrder: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  StalemateAction dco_decode_stalemate_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StalemateAction.values[raw as int];
  }

  @protected
  TgfAction dco_decode_tgf_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TgfAction(
      kindTag: dco_decode_i_32(arr[0]),
      fromNode: dco_decode_i_32(arr[1]),
      toNode: dco_decode_i_32(arr[2]),
      aux: dco_decode_i_32(arr[3]),
      payloadBits: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  TgfOutcome dco_decode_tgf_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TgfOutcome(
      kind: dco_decode_String(arr[0]),
      winner: dco_decode_i_32(arr[1]),
      reason: dco_decode_String(arr[2]),
    );
  }

  @protected
  TgfSnapshot dco_decode_tgf_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TgfSnapshot(
      sideToMove: dco_decode_i_32(arr[0]),
      phaseTag: dco_decode_i_32(arr[1]),
      moveNumber: dco_decode_i_32(arr[2]),
      zobristKey: dco_decode_u_64(arr[3]),
      opaquePayload: dco_decode_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  TopologyBlob dco_decode_topology_blob(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TopologyBlob(
      name: dco_decode_String(arr[0]),
      points: dco_decode_list_topology_point(arr[1]),
      edges: dco_decode_list_topology_edge(arr[2]),
      lineGroups: dco_decode_list_list_prim_u_16_strict(arr[3]),
    );
  }

  @protected
  TopologyEdge dco_decode_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TopologyEdge(
      a: dco_decode_u_16(arr[0]),
      b: dco_decode_u_16(arr[1]),
      kindTag: dco_decode_u_16(arr[2]),
    );
  }

  @protected
  TopologyPoint dco_decode_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TopologyPoint(
      id: dco_decode_u_16(arr[0]),
      square: dco_decode_u_16(arr[1]),
      label: dco_decode_String(arr[2]),
      x: dco_decode_f_32(arr[3]),
      y: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<EngineEvent> sse_decode_StreamSink_engine_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MillEngineConfig sse_decode_box_autoadd_mill_engine_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mill_engine_config(deserializer));
  }

  @protected
  MillVariantOptions sse_decode_box_autoadd_mill_variant_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mill_variant_options(deserializer));
  }

  @protected
  TgfAction sse_decode_box_autoadd_tgf_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tgf_action(deserializer));
  }

  @protected
  CaptureRuleConfig sse_decode_capture_rule_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_onSquareEdges = sse_decode_bool(deserializer);
    var var_onCrossLines = sse_decode_bool(deserializer);
    var var_onDiagonalLines = sse_decode_bool(deserializer);
    var var_inPlacingPhase = sse_decode_bool(deserializer);
    var var_inMovingPhase = sse_decode_bool(deserializer);
    var var_onlyAvailableWhenOwnPiecesLeq3 = sse_decode_bool(deserializer);
    return CaptureRuleConfig(
      enabled: var_enabled,
      onSquareEdges: var_onSquareEdges,
      onCrossLines: var_onCrossLines,
      onDiagonalLines: var_onDiagonalLines,
      inPlacingPhase: var_inPlacingPhase,
      inMovingPhase: var_inMovingPhase,
      onlyAvailableWhenOwnPiecesLeq3: var_onlyAvailableWhenOwnPiecesLeq3,
    );
  }

  @protected
  EngineEvent sse_decode_engine_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_depth = sse_decode_i_32(deserializer);
    var var_score = sse_decode_i_32(deserializer);
    var var_nodes = sse_decode_u_64(deserializer);
    var var_toNode = sse_decode_i_32(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return EngineEvent(
      kind: var_kind,
      depth: var_depth,
      score: var_score,
      nodes: var_nodes,
      toNode: var_toNode,
      reason: var_reason,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Uint16List> sse_decode_list_list_prim_u_16_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint16List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_16_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TgfAction> sse_decode_list_tgf_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TgfAction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tgf_action(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopologyEdge> sse_decode_list_topology_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopologyEdge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopologyPoint> sse_decode_list_topology_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopologyPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_point(deserializer));
    }
    return ans_;
  }

  @protected
  MillBoardFullAction sse_decode_mill_board_full_action(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MillBoardFullAction.values[inner];
  }

  @protected
  MillEngineConfig sse_decode_mill_engine_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_algorithm = sse_decode_mill_search_algorithm(deserializer);
    var var_depth = sse_decode_i_32(deserializer);
    var var_moveTimeMs = sse_decode_u_32(deserializer);
    var var_aiIsLazy = sse_decode_bool(deserializer);
    var var_lastBestValue = sse_decode_i_32(deserializer);
    var var_skillLevel = sse_decode_u_8(deserializer);
    var var_usePerfectDatabase = sse_decode_bool(deserializer);
    return MillEngineConfig(
      algorithm: var_algorithm,
      depth: var_depth,
      moveTimeMs: var_moveTimeMs,
      aiIsLazy: var_aiIsLazy,
      lastBestValue: var_lastBestValue,
      skillLevel: var_skillLevel,
      usePerfectDatabase: var_usePerfectDatabase,
    );
  }

  @protected
  MillFormationActionInPlacingPhase
  sse_decode_mill_formation_action_in_placing_phase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MillFormationActionInPlacingPhase.values[inner];
  }

  @protected
  MillSearchAlgorithm sse_decode_mill_search_algorithm(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MillSearchAlgorithm.values[inner];
  }

  @protected
  MillVariantOptions sse_decode_mill_variant_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceCount = sse_decode_u_8(deserializer);
    var var_flyPieceCount = sse_decode_u_8(deserializer);
    var var_piecesAtLeastCount = sse_decode_u_8(deserializer);
    var var_mayFly = sse_decode_bool(deserializer);
    var var_hasDiagonalLines = sse_decode_bool(deserializer);
    var var_millFormationActionInPlacingPhase =
        sse_decode_mill_formation_action_in_placing_phase(deserializer);
    var var_mayRemoveFromMillsAlways = sse_decode_bool(deserializer);
    var var_mayRemoveMultiple = sse_decode_bool(deserializer);
    var var_nMoveRule = sse_decode_u_32(deserializer);
    var var_endgameNMoveRule = sse_decode_u_32(deserializer);
    var var_mayMoveInPlacingPhase = sse_decode_bool(deserializer);
    var var_isDefenderMoveFirst = sse_decode_bool(deserializer);
    var var_restrictRepeatedMillsFormation = sse_decode_bool(deserializer);
    var var_oneTimeUseMill = sse_decode_bool(deserializer);
    var var_stopPlacingWhenTwoEmptySquares = sse_decode_bool(deserializer);
    var var_boardFullAction = sse_decode_mill_board_full_action(deserializer);
    var var_threefoldRepetitionRule = sse_decode_bool(deserializer);
    var var_custodianCapture = sse_decode_capture_rule_config(deserializer);
    var var_interventionCapture = sse_decode_capture_rule_config(deserializer);
    var var_leapCapture = sse_decode_capture_rule_config(deserializer);
    var var_stalemateAction = sse_decode_stalemate_action(deserializer);
    var var_considerMobility = sse_decode_bool(deserializer);
    var var_focusOnBlockingPaths = sse_decode_bool(deserializer);
    return MillVariantOptions(
      pieceCount: var_pieceCount,
      flyPieceCount: var_flyPieceCount,
      piecesAtLeastCount: var_piecesAtLeastCount,
      mayFly: var_mayFly,
      hasDiagonalLines: var_hasDiagonalLines,
      millFormationActionInPlacingPhase: var_millFormationActionInPlacingPhase,
      mayRemoveFromMillsAlways: var_mayRemoveFromMillsAlways,
      mayRemoveMultiple: var_mayRemoveMultiple,
      nMoveRule: var_nMoveRule,
      endgameNMoveRule: var_endgameNMoveRule,
      mayMoveInPlacingPhase: var_mayMoveInPlacingPhase,
      isDefenderMoveFirst: var_isDefenderMoveFirst,
      restrictRepeatedMillsFormation: var_restrictRepeatedMillsFormation,
      oneTimeUseMill: var_oneTimeUseMill,
      stopPlacingWhenTwoEmptySquares: var_stopPlacingWhenTwoEmptySquares,
      boardFullAction: var_boardFullAction,
      threefoldRepetitionRule: var_threefoldRepetitionRule,
      custodianCapture: var_custodianCapture,
      interventionCapture: var_interventionCapture,
      leapCapture: var_leapCapture,
      stalemateAction: var_stalemateAction,
      considerMobility: var_considerMobility,
      focusOnBlockingPaths: var_focusOnBlockingPaths,
    );
  }

  @protected
  PlayerInfoBlob sse_decode_player_info_blob(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playerCount = sse_decode_u_8(deserializer);
    var var_teamOf = sse_decode_list_prim_u_8_strict(deserializer);
    var var_turnOrder = sse_decode_list_prim_u_8_strict(deserializer);
    return PlayerInfoBlob(
      playerCount: var_playerCount,
      teamOf: var_teamOf,
      turnOrder: var_turnOrder,
    );
  }

  @protected
  StalemateAction sse_decode_stalemate_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StalemateAction.values[inner];
  }

  @protected
  TgfAction sse_decode_tgf_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kindTag = sse_decode_i_32(deserializer);
    var var_fromNode = sse_decode_i_32(deserializer);
    var var_toNode = sse_decode_i_32(deserializer);
    var var_aux = sse_decode_i_32(deserializer);
    var var_payloadBits = sse_decode_u_64(deserializer);
    return TgfAction(
      kindTag: var_kindTag,
      fromNode: var_fromNode,
      toNode: var_toNode,
      aux: var_aux,
      payloadBits: var_payloadBits,
    );
  }

  @protected
  TgfOutcome sse_decode_tgf_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_winner = sse_decode_i_32(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return TgfOutcome(kind: var_kind, winner: var_winner, reason: var_reason);
  }

  @protected
  TgfSnapshot sse_decode_tgf_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sideToMove = sse_decode_i_32(deserializer);
    var var_phaseTag = sse_decode_i_32(deserializer);
    var var_moveNumber = sse_decode_i_32(deserializer);
    var var_zobristKey = sse_decode_u_64(deserializer);
    var var_opaquePayload = sse_decode_list_prim_u_8_strict(deserializer);
    return TgfSnapshot(
      sideToMove: var_sideToMove,
      phaseTag: var_phaseTag,
      moveNumber: var_moveNumber,
      zobristKey: var_zobristKey,
      opaquePayload: var_opaquePayload,
    );
  }

  @protected
  TopologyBlob sse_decode_topology_blob(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_points = sse_decode_list_topology_point(deserializer);
    var var_edges = sse_decode_list_topology_edge(deserializer);
    var var_lineGroups = sse_decode_list_list_prim_u_16_strict(deserializer);
    return TopologyBlob(
      name: var_name,
      points: var_points,
      edges: var_edges,
      lineGroups: var_lineGroups,
    );
  }

  @protected
  TopologyEdge sse_decode_topology_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a = sse_decode_u_16(deserializer);
    var var_b = sse_decode_u_16(deserializer);
    var var_kindTag = sse_decode_u_16(deserializer);
    return TopologyEdge(a: var_a, b: var_b, kindTag: var_kindTag);
  }

  @protected
  TopologyPoint sse_decode_topology_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_16(deserializer);
    var var_square = sse_decode_u_16(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    return TopologyPoint(
      id: var_id,
      square: var_square,
      label: var_label,
      x: var_x,
      y: var_y,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_engine_event_Sse(
    RustStreamSink<EngineEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mill_engine_config(
    MillEngineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mill_engine_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mill_variant_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tgf_action(
    TgfAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tgf_action(self, serializer);
  }

  @protected
  void sse_encode_capture_rule_config(
    CaptureRuleConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_bool(self.onSquareEdges, serializer);
    sse_encode_bool(self.onCrossLines, serializer);
    sse_encode_bool(self.onDiagonalLines, serializer);
    sse_encode_bool(self.inPlacingPhase, serializer);
    sse_encode_bool(self.inMovingPhase, serializer);
    sse_encode_bool(self.onlyAvailableWhenOwnPiecesLeq3, serializer);
  }

  @protected
  void sse_encode_engine_event(EngineEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_i_32(self.depth, serializer);
    sse_encode_i_32(self.score, serializer);
    sse_encode_u_64(self.nodes, serializer);
    sse_encode_i_32(self.toNode, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_list_prim_u_16_strict(
    List<Uint16List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_16_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_tgf_action(
    List<TgfAction> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tgf_action(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topology_edge(
    List<TopologyEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topology_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topology_point(
    List<TopologyPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topology_point(item, serializer);
    }
  }

  @protected
  void sse_encode_mill_board_full_action(
    MillBoardFullAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mill_engine_config(
    MillEngineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mill_search_algorithm(self.algorithm, serializer);
    sse_encode_i_32(self.depth, serializer);
    sse_encode_u_32(self.moveTimeMs, serializer);
    sse_encode_bool(self.aiIsLazy, serializer);
    sse_encode_i_32(self.lastBestValue, serializer);
    sse_encode_u_8(self.skillLevel, serializer);
    sse_encode_bool(self.usePerfectDatabase, serializer);
  }

  @protected
  void sse_encode_mill_formation_action_in_placing_phase(
    MillFormationActionInPlacingPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mill_search_algorithm(
    MillSearchAlgorithm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pieceCount, serializer);
    sse_encode_u_8(self.flyPieceCount, serializer);
    sse_encode_u_8(self.piecesAtLeastCount, serializer);
    sse_encode_bool(self.mayFly, serializer);
    sse_encode_bool(self.hasDiagonalLines, serializer);
    sse_encode_mill_formation_action_in_placing_phase(
      self.millFormationActionInPlacingPhase,
      serializer,
    );
    sse_encode_bool(self.mayRemoveFromMillsAlways, serializer);
    sse_encode_bool(self.mayRemoveMultiple, serializer);
    sse_encode_u_32(self.nMoveRule, serializer);
    sse_encode_u_32(self.endgameNMoveRule, serializer);
    sse_encode_bool(self.mayMoveInPlacingPhase, serializer);
    sse_encode_bool(self.isDefenderMoveFirst, serializer);
    sse_encode_bool(self.restrictRepeatedMillsFormation, serializer);
    sse_encode_bool(self.oneTimeUseMill, serializer);
    sse_encode_bool(self.stopPlacingWhenTwoEmptySquares, serializer);
    sse_encode_mill_board_full_action(self.boardFullAction, serializer);
    sse_encode_bool(self.threefoldRepetitionRule, serializer);
    sse_encode_capture_rule_config(self.custodianCapture, serializer);
    sse_encode_capture_rule_config(self.interventionCapture, serializer);
    sse_encode_capture_rule_config(self.leapCapture, serializer);
    sse_encode_stalemate_action(self.stalemateAction, serializer);
    sse_encode_bool(self.considerMobility, serializer);
    sse_encode_bool(self.focusOnBlockingPaths, serializer);
  }

  @protected
  void sse_encode_player_info_blob(
    PlayerInfoBlob self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.playerCount, serializer);
    sse_encode_list_prim_u_8_strict(self.teamOf, serializer);
    sse_encode_list_prim_u_8_strict(self.turnOrder, serializer);
  }

  @protected
  void sse_encode_stalemate_action(
    StalemateAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tgf_action(TgfAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.kindTag, serializer);
    sse_encode_i_32(self.fromNode, serializer);
    sse_encode_i_32(self.toNode, serializer);
    sse_encode_i_32(self.aux, serializer);
    sse_encode_u_64(self.payloadBits, serializer);
  }

  @protected
  void sse_encode_tgf_outcome(TgfOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_i_32(self.winner, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_tgf_snapshot(TgfSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.sideToMove, serializer);
    sse_encode_i_32(self.phaseTag, serializer);
    sse_encode_i_32(self.moveNumber, serializer);
    sse_encode_u_64(self.zobristKey, serializer);
    sse_encode_list_prim_u_8_strict(self.opaquePayload, serializer);
  }

  @protected
  void sse_encode_topology_blob(TopologyBlob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_topology_point(self.points, serializer);
    sse_encode_list_topology_edge(self.edges, serializer);
    sse_encode_list_list_prim_u_16_strict(self.lineGroups, serializer);
  }

  @protected
  void sse_encode_topology_edge(TopologyEdge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.a, serializer);
    sse_encode_u_16(self.b, serializer);
    sse_encode_u_16(self.kindTag, serializer);
  }

  @protected
  void sse_encode_topology_point(TopologyPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.id, serializer);
    sse_encode_u_16(self.square, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
