// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/simple.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final RustLib instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -819536247;

  static const ExternalLibraryLoaderConfig kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_sanmill',
        ioDirectory: '../../../crates/tgf-frb/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  TopologyBlob crateApiSimpleKernelTopology();

  bool crateApiSimpleLegacyKernelApplyUci({required String moveUci});

  String crateApiSimpleLegacyKernelFen();

  List<String> crateApiSimpleLegacyKernelLegalActions();

  int crateApiSimpleLegacyKernelPhaseTag();

  String crateApiSimpleLegacyKernelReset({required int ruleIdx});

  int crateApiSimpleLegacyKernelSideToMove();

  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove();

  int crateApiSimpleNativeMillInitialLegalCount();

  int crateApiSimpleNativeMillMillSequenceRemoveCount();

  String crateApiSimpleTgfHelloWorld();

  String crateApiSimpleTgfVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (NativePortType port_) {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: <String>[]);

  @override
  TopologyBlob crateApiSimpleKernelTopology() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_topology_blob,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleKernelTopologyConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleKernelTopologyConstMeta =>
      const TaskConstMeta(debugName: "kernel_topology", argNames: <String>[]);

  @override
  bool crateApiSimpleLegacyKernelApplyUci({required String moveUci}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_String(moveUci, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelApplyUciConstMeta,
        argValues: <dynamic>[moveUci],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelApplyUciConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_apply_uci",
        argNames: <String>["moveUci"],
      );

  @override
  String crateApiSimpleLegacyKernelFen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelFenConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelFenConstMeta =>
      const TaskConstMeta(debugName: "legacy_kernel_fen", argNames: <String>[]);

  @override
  List<String> crateApiSimpleLegacyKernelLegalActions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelLegalActionsConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelLegalActionsConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_legal_actions",
        argNames: <String>[],
      );

  @override
  int crateApiSimpleLegacyKernelPhaseTag() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelPhaseTagConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelPhaseTagConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_phase_tag",
        argNames: <String>[],
      );

  @override
  String crateApiSimpleLegacyKernelReset({required int ruleIdx}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_i_32(ruleIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelResetConstMeta,
        argValues: <dynamic>[ruleIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelResetConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_reset",
        argNames: <String>["ruleIdx"],
      );

  @override
  int crateApiSimpleLegacyKernelSideToMove() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelSideToMoveConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelSideToMoveConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_side_to_move",
        argNames: <String>[],
      );

  @override
  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_apply_first_place_side_to_move",
        argNames: <String>[],
      );

  @override
  int crateApiSimpleNativeMillInitialLegalCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillInitialLegalCountConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillInitialLegalCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_initial_legal_count",
        argNames: <String>[],
      );

  @override
  int crateApiSimpleNativeMillMillSequenceRemoveCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_mill_sequence_remove_count",
        argNames: <String>[],
      );

  @override
  String crateApiSimpleTgfHelloWorld() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfHelloWorldConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "tgf_hello_world", argNames: <String>[]);

  @override
  String crateApiSimpleTgfVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfVersionConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfVersionConstMeta =>
      const TaskConstMeta(debugName: "tgf_version", argNames: <String>[]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint16List> dco_decode_list_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_u_16_strict)
        .toList();
  }

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TopologyEdge> dco_decode_list_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_edge).toList();
  }

  @protected
  List<TopologyPoint> dco_decode_list_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_point).toList();
  }

  @protected
  TopologyBlob dco_decode_topology_blob(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TopologyBlob(
      name: dco_decode_String(arr[0]),
      points: dco_decode_list_topology_point(arr[1]),
      edges: dco_decode_list_topology_edge(arr[2]),
      lineGroups: dco_decode_list_list_prim_u_16_strict(arr[3]),
    );
  }

  @protected
  TopologyEdge dco_decode_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TopologyEdge(a: dco_decode_u_16(arr[0]), b: dco_decode_u_16(arr[1]));
  }

  @protected
  TopologyPoint dco_decode_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TopologyPoint(
      id: dco_decode_u_16(arr[0]),
      square: dco_decode_u_16(arr[1]),
      label: dco_decode_String(arr[2]),
      x: dco_decode_f_32(arr[3]),
      y: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final Uint8List inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<String> ans_ = <String>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint16List> sse_decode_list_list_prim_u_16_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<Uint16List> ans_ = <Uint16List>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_16_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TopologyEdge> sse_decode_list_topology_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<TopologyEdge> ans_ = <TopologyEdge>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopologyPoint> sse_decode_list_topology_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<TopologyPoint> ans_ = <TopologyPoint>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_point(deserializer));
    }
    return ans_;
  }

  @protected
  TopologyBlob sse_decode_topology_blob(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final String var_name = sse_decode_String(deserializer);
    final List<TopologyPoint> var_points = sse_decode_list_topology_point(
      deserializer,
    );
    final List<TopologyEdge> var_edges = sse_decode_list_topology_edge(
      deserializer,
    );
    final List<Uint16List> var_lineGroups =
        sse_decode_list_list_prim_u_16_strict(deserializer);
    return TopologyBlob(
      name: var_name,
      points: var_points,
      edges: var_edges,
      lineGroups: var_lineGroups,
    );
  }

  @protected
  TopologyEdge sse_decode_topology_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int var_a = sse_decode_u_16(deserializer);
    final int var_b = sse_decode_u_16(deserializer);
    return TopologyEdge(a: var_a, b: var_b);
  }

  @protected
  TopologyPoint sse_decode_topology_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int var_id = sse_decode_u_16(deserializer);
    final int var_square = sse_decode_u_16(deserializer);
    final String var_label = sse_decode_String(deserializer);
    final double var_x = sse_decode_f_32(deserializer);
    final double var_y = sse_decode_f_32(deserializer);
    return TopologyPoint(
      id: var_id,
      square: var_square,
      label: var_label,
      x: var_x,
      y: var_y,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final String item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_16_strict(
    List<Uint16List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final Uint16List item in self) {
      sse_encode_list_prim_u_16_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_topology_edge(
    List<TopologyEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final TopologyEdge item in self) {
      sse_encode_topology_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topology_point(
    List<TopologyPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final TopologyPoint item in self) {
      sse_encode_topology_point(item, serializer);
    }
  }

  @protected
  void sse_encode_topology_blob(TopologyBlob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_topology_point(self.points, serializer);
    sse_encode_list_topology_edge(self.edges, serializer);
    sse_encode_list_list_prim_u_16_strict(self.lineGroups, serializer);
  }

  @protected
  void sse_encode_topology_edge(TopologyEdge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.a, serializer);
    sse_encode_u_16(self.b, serializer);
  }

  @protected
  void sse_encode_topology_point(TopologyPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.id, serializer);
    sse_encode_u_16(self.square, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
