// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -798849941;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_sanmill',
        ioDirectory: '../../../crates/tgf-frb/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  TopologyBlob crateApiSimpleKernelTopology();

  bool crateApiSimpleLegacyKernelApplyUci({required String moveUci});

  String crateApiSimpleLegacyKernelFen();

  List<String> crateApiSimpleLegacyKernelLegalActions();

  int crateApiSimpleLegacyKernelPhaseTag();

  String crateApiSimpleLegacyKernelReset({required int ruleIdx});

  void crateApiSimpleLegacyKernelSetFen({required String fen});

  int crateApiSimpleLegacyKernelSideToMove();

  bool crateApiSimpleNativeAndLegacyMovingPhasePerftMatch({required int depth});

  bool crateApiSimpleNativeAndLegacyPendingRemovePerftMatch({
    required int depth,
  });

  bool crateApiSimpleNativeAndLegacyPerftMatch({required int depth});

  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove();

  MillVariantOptions crateApiSimpleNativeMillDefaultVariantOptions();

  int crateApiSimpleNativeMillInitialLegalCount();

  int crateApiSimpleNativeMillInitialLegalCountForVariant({
    required MillVariantOptions variant,
  });

  int crateApiSimpleNativeMillMctsBestToNode({
    required BigInt seed,
    required int iterationsPerMove,
  });

  int crateApiSimpleNativeMillMillSequenceRemoveCount();

  int crateApiSimpleNativeMillMovingMillRemoveCount();

  int crateApiSimpleNativeMillPvsDepthOneBestToNode();

  int crateApiSimpleNativeMillRandomBestToNode({required BigInt seed});

  int crateApiSimpleNativeMillRemovalBelowThreeWinner();

  int crateApiSimpleNativeMillSearchDepthOneBestToNode();

  Stream<EngineEvent> crateApiSimpleNativeMillSearchEvents({
    required int depth,
  });

  bool crateApiSimpleNativeMillSearchStop();

  bool crateApiSimpleNativeMillSearchZeroTimeLimitAborts();

  int crateApiSimpleNativeOthelloInitialLegalCount();

  int crateApiSimpleNativeOthelloSearchDepthOneBestToNode();

  String crateApiSimpleTgfHelloWorld();

  String crateApiSimpleTgfVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  TopologyBlob crateApiSimpleKernelTopology() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_topology_blob,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleKernelTopologyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleKernelTopologyConstMeta =>
      const TaskConstMeta(debugName: "kernel_topology", argNames: []);

  @override
  bool crateApiSimpleLegacyKernelApplyUci({required String moveUci}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moveUci, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelApplyUciConstMeta,
        argValues: [moveUci],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelApplyUciConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_apply_uci",
        argNames: ["moveUci"],
      );

  @override
  String crateApiSimpleLegacyKernelFen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelFenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelFenConstMeta =>
      const TaskConstMeta(debugName: "legacy_kernel_fen", argNames: []);

  @override
  List<String> crateApiSimpleLegacyKernelLegalActions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelLegalActionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelLegalActionsConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_legal_actions",
        argNames: [],
      );

  @override
  int crateApiSimpleLegacyKernelPhaseTag() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelPhaseTagConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelPhaseTagConstMeta =>
      const TaskConstMeta(debugName: "legacy_kernel_phase_tag", argNames: []);

  @override
  String crateApiSimpleLegacyKernelReset({required int ruleIdx}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(ruleIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelResetConstMeta,
        argValues: [ruleIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelResetConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_reset",
        argNames: ["ruleIdx"],
      );

  @override
  void crateApiSimpleLegacyKernelSetFen({required String fen}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelSetFenConstMeta,
        argValues: [fen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelSetFenConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_set_fen",
        argNames: ["fen"],
      );

  @override
  int crateApiSimpleLegacyKernelSideToMove() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLegacyKernelSideToMoveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLegacyKernelSideToMoveConstMeta =>
      const TaskConstMeta(
        debugName: "legacy_kernel_side_to_move",
        argNames: [],
      );

  @override
  bool crateApiSimpleNativeAndLegacyMovingPhasePerftMatch({
    required int depth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(depth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeAndLegacyMovingPhasePerftMatchConstMeta,
        argValues: [depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeAndLegacyMovingPhasePerftMatchConstMeta =>
      const TaskConstMeta(
        debugName: "native_and_legacy_moving_phase_perft_match",
        argNames: ["depth"],
      );

  @override
  bool crateApiSimpleNativeAndLegacyPendingRemovePerftMatch({
    required int depth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(depth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleNativeAndLegacyPendingRemovePerftMatchConstMeta,
        argValues: [depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeAndLegacyPendingRemovePerftMatchConstMeta =>
      const TaskConstMeta(
        debugName: "native_and_legacy_pending_remove_perft_match",
        argNames: ["depth"],
      );

  @override
  bool crateApiSimpleNativeAndLegacyPerftMatch({required int depth}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(depth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeAndLegacyPerftMatchConstMeta,
        argValues: [depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeAndLegacyPerftMatchConstMeta =>
      const TaskConstMeta(
        debugName: "native_and_legacy_perft_match",
        argNames: ["depth"],
      );

  @override
  int crateApiSimpleNativeMillApplyFirstPlaceSideToMove() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillApplyFirstPlaceSideToMoveConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_apply_first_place_side_to_move",
        argNames: [],
      );

  @override
  MillVariantOptions crateApiSimpleNativeMillDefaultVariantOptions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mill_variant_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillDefaultVariantOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillDefaultVariantOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_default_variant_options",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillInitialLegalCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillInitialLegalCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillInitialLegalCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_initial_legal_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillInitialLegalCountForVariant({
    required MillVariantOptions variant,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mill_variant_options(variant, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleNativeMillInitialLegalCountForVariantConstMeta,
        argValues: [variant],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillInitialLegalCountForVariantConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_initial_legal_count_for_variant",
        argNames: ["variant"],
      );

  @override
  int crateApiSimpleNativeMillMctsBestToNode({
    required BigInt seed,
    required int iterationsPerMove,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seed, serializer);
          sse_encode_u_32(iterationsPerMove, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMctsBestToNodeConstMeta,
        argValues: [seed, iterationsPerMove],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMctsBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_mcts_best_to_node",
        argNames: ["seed", "iterationsPerMove"],
      );

  @override
  int crateApiSimpleNativeMillMillSequenceRemoveCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMillSequenceRemoveCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_mill_sequence_remove_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillMovingMillRemoveCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillMovingMillRemoveCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillMovingMillRemoveCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_moving_mill_remove_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillPvsDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillPvsDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillPvsDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_pvs_depth_one_best_to_node",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillRandomBestToNode({required BigInt seed}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillRandomBestToNodeConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillRandomBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_random_best_to_node",
        argNames: ["seed"],
      );

  @override
  int crateApiSimpleNativeMillRemovalBelowThreeWinner() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillRemovalBelowThreeWinnerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillRemovalBelowThreeWinnerConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_removal_below_three_winner",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeMillSearchDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillSearchDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_depth_one_best_to_node",
        argNames: [],
      );

  @override
  Stream<EngineEvent> crateApiSimpleNativeMillSearchEvents({
    required int depth,
  }) {
    final sink = RustStreamSink<EngineEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_32(depth, serializer);
            sse_encode_StreamSink_engine_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 24,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleNativeMillSearchEventsConstMeta,
          argValues: [depth, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleNativeMillSearchEventsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_events",
        argNames: ["depth", "sink"],
      );

  @override
  bool crateApiSimpleNativeMillSearchStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeMillSearchStopConstMeta =>
      const TaskConstMeta(debugName: "native_mill_search_stop", argNames: []);

  @override
  bool crateApiSimpleNativeMillSearchZeroTimeLimitAborts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeMillSearchZeroTimeLimitAbortsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeMillSearchZeroTimeLimitAbortsConstMeta =>
      const TaskConstMeta(
        debugName: "native_mill_search_zero_time_limit_aborts",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeOthelloInitialLegalCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNativeOthelloInitialLegalCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNativeOthelloInitialLegalCountConstMeta =>
      const TaskConstMeta(
        debugName: "native_othello_initial_legal_count",
        argNames: [],
      );

  @override
  int crateApiSimpleNativeOthelloSearchDepthOneBestToNode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleNativeOthelloSearchDepthOneBestToNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleNativeOthelloSearchDepthOneBestToNodeConstMeta =>
      const TaskConstMeta(
        debugName: "native_othello_search_depth_one_best_to_node",
        argNames: [],
      );

  @override
  String crateApiSimpleTgfHelloWorld() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfHelloWorldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "tgf_hello_world", argNames: []);

  @override
  String crateApiSimpleTgfVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTgfVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTgfVersionConstMeta =>
      const TaskConstMeta(debugName: "tgf_version", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<EngineEvent> dco_decode_StreamSink_engine_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MillVariantOptions dco_decode_box_autoadd_mill_variant_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mill_variant_options(raw);
  }

  @protected
  EngineEvent dco_decode_engine_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EngineEvent(
      kind: dco_decode_String(arr[0]),
      depth: dco_decode_i_32(arr[1]),
      score: dco_decode_i_32(arr[2]),
      nodes: dco_decode_u_64(arr[3]),
      toNode: dco_decode_i_32(arr[4]),
      reason: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint16List> dco_decode_list_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_u_16_strict)
        .toList();
  }

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TopologyEdge> dco_decode_list_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_edge).toList();
  }

  @protected
  List<TopologyPoint> dco_decode_list_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_topology_point).toList();
  }

  @protected
  MillVariantOptions dco_decode_mill_variant_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MillVariantOptions(
      pieceCount: dco_decode_u_8(arr[0]),
      flyPieceCount: dco_decode_u_8(arr[1]),
      piecesAtLeastCount: dco_decode_u_8(arr[2]),
      mayFly: dco_decode_bool(arr[3]),
      hasDiagonalLines: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TopologyBlob dco_decode_topology_blob(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TopologyBlob(
      name: dco_decode_String(arr[0]),
      points: dco_decode_list_topology_point(arr[1]),
      edges: dco_decode_list_topology_edge(arr[2]),
      lineGroups: dco_decode_list_list_prim_u_16_strict(arr[3]),
    );
  }

  @protected
  TopologyEdge dco_decode_topology_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TopologyEdge(a: dco_decode_u_16(arr[0]), b: dco_decode_u_16(arr[1]));
  }

  @protected
  TopologyPoint dco_decode_topology_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TopologyPoint(
      id: dco_decode_u_16(arr[0]),
      square: dco_decode_u_16(arr[1]),
      label: dco_decode_String(arr[2]),
      x: dco_decode_f_32(arr[3]),
      y: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<EngineEvent> sse_decode_StreamSink_engine_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MillVariantOptions sse_decode_box_autoadd_mill_variant_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mill_variant_options(deserializer));
  }

  @protected
  EngineEvent sse_decode_engine_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_depth = sse_decode_i_32(deserializer);
    var var_score = sse_decode_i_32(deserializer);
    var var_nodes = sse_decode_u_64(deserializer);
    var var_toNode = sse_decode_i_32(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return EngineEvent(
      kind: var_kind,
      depth: var_depth,
      score: var_score,
      nodes: var_nodes,
      toNode: var_toNode,
      reason: var_reason,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint16List> sse_decode_list_list_prim_u_16_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint16List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_16_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TopologyEdge> sse_decode_list_topology_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopologyEdge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<TopologyPoint> sse_decode_list_topology_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TopologyPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_topology_point(deserializer));
    }
    return ans_;
  }

  @protected
  MillVariantOptions sse_decode_mill_variant_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceCount = sse_decode_u_8(deserializer);
    var var_flyPieceCount = sse_decode_u_8(deserializer);
    var var_piecesAtLeastCount = sse_decode_u_8(deserializer);
    var var_mayFly = sse_decode_bool(deserializer);
    var var_hasDiagonalLines = sse_decode_bool(deserializer);
    return MillVariantOptions(
      pieceCount: var_pieceCount,
      flyPieceCount: var_flyPieceCount,
      piecesAtLeastCount: var_piecesAtLeastCount,
      mayFly: var_mayFly,
      hasDiagonalLines: var_hasDiagonalLines,
    );
  }

  @protected
  TopologyBlob sse_decode_topology_blob(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_points = sse_decode_list_topology_point(deserializer);
    var var_edges = sse_decode_list_topology_edge(deserializer);
    var var_lineGroups = sse_decode_list_list_prim_u_16_strict(deserializer);
    return TopologyBlob(
      name: var_name,
      points: var_points,
      edges: var_edges,
      lineGroups: var_lineGroups,
    );
  }

  @protected
  TopologyEdge sse_decode_topology_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a = sse_decode_u_16(deserializer);
    var var_b = sse_decode_u_16(deserializer);
    return TopologyEdge(a: var_a, b: var_b);
  }

  @protected
  TopologyPoint sse_decode_topology_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_16(deserializer);
    var var_square = sse_decode_u_16(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    return TopologyPoint(
      id: var_id,
      square: var_square,
      label: var_label,
      x: var_x,
      y: var_y,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_engine_event_Sse(
    RustStreamSink<EngineEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mill_variant_options(self, serializer);
  }

  @protected
  void sse_encode_engine_event(EngineEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_i_32(self.depth, serializer);
    sse_encode_i_32(self.score, serializer);
    sse_encode_u_64(self.nodes, serializer);
    sse_encode_i_32(self.toNode, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_16_strict(
    List<Uint16List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_16_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_topology_edge(
    List<TopologyEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topology_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_topology_point(
    List<TopologyPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_topology_point(item, serializer);
    }
  }

  @protected
  void sse_encode_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pieceCount, serializer);
    sse_encode_u_8(self.flyPieceCount, serializer);
    sse_encode_u_8(self.piecesAtLeastCount, serializer);
    sse_encode_bool(self.mayFly, serializer);
    sse_encode_bool(self.hasDiagonalLines, serializer);
  }

  @protected
  void sse_encode_topology_blob(TopologyBlob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_topology_point(self.points, serializer);
    sse_encode_list_topology_edge(self.edges, serializer);
    sse_encode_list_list_prim_u_16_strict(self.lineGroups, serializer);
  }

  @protected
  void sse_encode_topology_edge(TopologyEdge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.a, serializer);
    sse_encode_u_16(self.b, serializer);
  }

  @protected
  void sse_encode_topology_point(TopologyPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.id, serializer);
    sse_encode_u_16(self.square, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
