// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/kernel.dart';
import 'api/mill_kernel.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EngineEvent> dco_decode_StreamSink_engine_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MillEngineConfig dco_decode_box_autoadd_mill_engine_config(dynamic raw);

  @protected
  MillVariantOptions dco_decode_box_autoadd_mill_variant_options(dynamic raw);

  @protected
  TgfAction dco_decode_box_autoadd_tgf_action(dynamic raw);

  @protected
  CaptureRuleConfig dco_decode_capture_rule_config(dynamic raw);

  @protected
  EngineEvent dco_decode_engine_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<Uint16List> dco_decode_list_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TgfAction> dco_decode_list_tgf_action(dynamic raw);

  @protected
  List<TopologyEdge> dco_decode_list_topology_edge(dynamic raw);

  @protected
  List<TopologyPoint> dco_decode_list_topology_point(dynamic raw);

  @protected
  MillBoardFullAction dco_decode_mill_board_full_action(dynamic raw);

  @protected
  MillEngineConfig dco_decode_mill_engine_config(dynamic raw);

  @protected
  MillFormationActionInPlacingPhase
  dco_decode_mill_formation_action_in_placing_phase(dynamic raw);

  @protected
  MillSearchAlgorithm dco_decode_mill_search_algorithm(dynamic raw);

  @protected
  MillVariantOptions dco_decode_mill_variant_options(dynamic raw);

  @protected
  PlayerInfoBlob dco_decode_player_info_blob(dynamic raw);

  @protected
  StalemateAction dco_decode_stalemate_action(dynamic raw);

  @protected
  TgfAction dco_decode_tgf_action(dynamic raw);

  @protected
  TgfOutcome dco_decode_tgf_outcome(dynamic raw);

  @protected
  TgfSnapshot dco_decode_tgf_snapshot(dynamic raw);

  @protected
  TopologyBlob dco_decode_topology_blob(dynamic raw);

  @protected
  TopologyEdge dco_decode_topology_edge(dynamic raw);

  @protected
  TopologyPoint dco_decode_topology_point(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EngineEvent> sse_decode_StreamSink_engine_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MillEngineConfig sse_decode_box_autoadd_mill_engine_config(
    SseDeserializer deserializer,
  );

  @protected
  MillVariantOptions sse_decode_box_autoadd_mill_variant_options(
    SseDeserializer deserializer,
  );

  @protected
  TgfAction sse_decode_box_autoadd_tgf_action(SseDeserializer deserializer);

  @protected
  CaptureRuleConfig sse_decode_capture_rule_config(
    SseDeserializer deserializer,
  );

  @protected
  EngineEvent sse_decode_engine_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<Uint16List> sse_decode_list_list_prim_u_16_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TgfAction> sse_decode_list_tgf_action(SseDeserializer deserializer);

  @protected
  List<TopologyEdge> sse_decode_list_topology_edge(
    SseDeserializer deserializer,
  );

  @protected
  List<TopologyPoint> sse_decode_list_topology_point(
    SseDeserializer deserializer,
  );

  @protected
  MillBoardFullAction sse_decode_mill_board_full_action(
    SseDeserializer deserializer,
  );

  @protected
  MillEngineConfig sse_decode_mill_engine_config(SseDeserializer deserializer);

  @protected
  MillFormationActionInPlacingPhase
  sse_decode_mill_formation_action_in_placing_phase(
    SseDeserializer deserializer,
  );

  @protected
  MillSearchAlgorithm sse_decode_mill_search_algorithm(
    SseDeserializer deserializer,
  );

  @protected
  MillVariantOptions sse_decode_mill_variant_options(
    SseDeserializer deserializer,
  );

  @protected
  PlayerInfoBlob sse_decode_player_info_blob(SseDeserializer deserializer);

  @protected
  StalemateAction sse_decode_stalemate_action(SseDeserializer deserializer);

  @protected
  TgfAction sse_decode_tgf_action(SseDeserializer deserializer);

  @protected
  TgfOutcome sse_decode_tgf_outcome(SseDeserializer deserializer);

  @protected
  TgfSnapshot sse_decode_tgf_snapshot(SseDeserializer deserializer);

  @protected
  TopologyBlob sse_decode_topology_blob(SseDeserializer deserializer);

  @protected
  TopologyEdge sse_decode_topology_edge(SseDeserializer deserializer);

  @protected
  TopologyPoint sse_decode_topology_point(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_engine_event_Sse(
    RustStreamSink<EngineEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mill_engine_config(
    MillEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tgf_action(
    TgfAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capture_rule_config(
    CaptureRuleConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_engine_event(EngineEvent self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_16_strict(
    List<Uint16List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tgf_action(
    List<TgfAction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_topology_edge(
    List<TopologyEdge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_topology_point(
    List<TopologyPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mill_board_full_action(
    MillBoardFullAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mill_engine_config(
    MillEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mill_formation_action_in_placing_phase(
    MillFormationActionInPlacingPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mill_search_algorithm(
    MillSearchAlgorithm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mill_variant_options(
    MillVariantOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_info_blob(
    PlayerInfoBlob self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stalemate_action(
    StalemateAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tgf_action(TgfAction self, SseSerializer serializer);

  @protected
  void sse_encode_tgf_outcome(TgfOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_tgf_snapshot(TgfSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_topology_blob(TopologyBlob self, SseSerializer serializer);

  @protected
  void sse_encode_topology_edge(TopologyEdge self, SseSerializer serializer);

  @protected
  void sse_encode_topology_point(TopologyPoint self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
