// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These functions are ignored because they are not marked as `pub`: `build_rules_default`, `from_action`, `from_outcome`, `from_snap`, `into_action`, `map_kernel_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Create a kernel for one of the built-in games using its default
/// variant options (`mill` ⇒ Nine Men's Morris, `othello` ⇒ standard
/// 8x8).  Returns the new session handle on success.
int tgfKernelCreate({required String gameId}) =>
    RustLib.instance.api.crateApiKernelTgfKernelCreate(gameId: gameId);

/// Create a Mill kernel with explicit variant options.  Use this once
/// the Flutter `RuleSettings` model is mapped through
/// `MillVariantOptionsMapper`.
int tgfKernelCreateMill({required MillVariantOptions variant}) =>
    RustLib.instance.api.crateApiKernelTgfKernelCreateMill(variant: variant);

/// Drop the session associated with `handle`.  Idempotent: invoking
/// twice is a no-op.
void tgfKernelDispose({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelDispose(handle: handle);

String tgfKernelGameId({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelGameId(handle: handle);

TgfSnapshot tgfKernelSnapshot({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSnapshot(handle: handle);

List<TgfAction> tgfKernelLegalActions({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelLegalActions(handle: handle);

TgfSnapshot tgfKernelApply({required int handle, required TgfAction action}) =>
    RustLib.instance.api.crateApiKernelTgfKernelApply(
      handle: handle,
      action: action,
    );

TgfSnapshot tgfKernelApplyUnchecked({
  required int handle,
  required TgfAction action,
}) => RustLib.instance.api.crateApiKernelTgfKernelApplyUnchecked(
  handle: handle,
  action: action,
);

TgfSnapshot tgfKernelUndo({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelUndo(handle: handle);

TgfSnapshot tgfKernelRedo({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelRedo(handle: handle);

TgfOutcome tgfKernelOutcome({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelOutcome(handle: handle);

bool tgfKernelIsTerminal({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelIsTerminal(handle: handle);

int tgfKernelUndoDepth({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelUndoDepth(handle: handle);

int tgfKernelRedoDepth({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelRedoDepth(handle: handle);

/// PVS search over the kernel's **current** Mill position, using the same
/// variant options as [tgf_kernel_create_mill].
///
/// Streams the same [EngineEvent] sequence as [crate::api::simple::native_mill_search_events]:
/// one `info` event per IDS depth, then `bestMove` + `stopped`.
Stream<EngineEvent> tgfKernelMillSearchEvents({
  required int handle,
  required int depth,
}) => RustLib.instance.api.crateApiKernelTgfKernelMillSearchEvents(
  handle: handle,
  depth: depth,
);

/// Full-config search over the kernel's **current** Mill position.
///
/// Accepts a [`MillEngineConfig`] that controls algorithm, depth, time limit
/// and lazy-search behaviour.  Preferred over [tgf_kernel_mill_search_events]
/// for production use once the Flutter side has migrated to the typed config.
Stream<EngineEvent> tgfKernelMillSearchEventsWithConfig({
  required int handle,
  required MillEngineConfig config,
}) => RustLib.instance.api.crateApiKernelTgfKernelMillSearchEventsWithConfig(
  handle: handle,
  config: config,
);

/// Clear the board associated with a Mill kernel handle and reset all pieces,
/// returning the fresh empty snapshot.  History and redo stacks are cleared.
///
/// This is the entry point for the Flutter setup-position flow: call
/// `tgf_kernel_setup_clear` first, then `tgf_kernel_setup_set_piece` for each
/// piece, then `tgf_kernel_setup_finish` to transition to a playable state.
TgfSnapshot tgfKernelSetupClear({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupClear(handle: handle);

/// Set or clear a single piece at `node` for a Mill kernel in setup mode.
///
/// `owner`: `1` = first player (White), `2` = second player (Black),
/// any other value = clear the square.
///
/// Call `tgf_kernel_setup_clear` before the first `set_piece` to start with
/// a blank board, then `tgf_kernel_setup_finish` when editing is complete.
TgfSnapshot tgfKernelSetupSetPiece({
  required int handle,
  required int node,
  required int owner,
}) => RustLib.instance.api.crateApiKernelTgfKernelSetupSetPiece(
  handle: handle,
  node: node,
  owner: owner,
);

/// Set the side to move for a Mill kernel in setup mode.
///
/// `side`: `0` = first player (White), `1` = second player (Black).
TgfSnapshot tgfKernelSetupSetSide({required int handle, required int side}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupSetSide(
      handle: handle,
      side: side,
    );

/// Finish the setup-position editing flow.
///
/// Determines whether the resulting board is in placing or moving phase
/// based on whether any pieces remain in hand, recomputes auxiliary fields,
/// and replaces the kernel state.  After this call the kernel can be used
/// for normal play (legal actions, apply, search).
TgfSnapshot tgfKernelSetupFinish({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupFinish(handle: handle);

/// Load a Mill board position from a FEN string (Phase 6.A.3.B).
///
/// The FEN must follow the legacy Dart/C++ engine format.  Returns the
/// new snapshot on success, or an error string on parse failure.
TgfSnapshot tgfKernelSetFromFen({required int handle, required String fen}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetFromFen(
      handle: handle,
      fen: fen,
    );

/// Export the current Mill kernel state as a FEN string (Phase 6.A.3.B).
String tgfKernelExportFen({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelExportFen(handle: handle);

/// Mirror of `tgf_core::Action` with i32 fields so FRB can ship it as
/// trivial dart `int` types.  Conversion is `From`-symmetric.
class TgfAction {
  final int kindTag;
  final int fromNode;
  final int toNode;
  final int aux;
  final BigInt payloadBits;

  const TgfAction({
    required this.kindTag,
    required this.fromNode,
    required this.toNode,
    required this.aux,
    required this.payloadBits,
  });

  @override
  int get hashCode =>
      kindTag.hashCode ^
      fromNode.hashCode ^
      toNode.hashCode ^
      aux.hashCode ^
      payloadBits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfAction &&
          runtimeType == other.runtimeType &&
          kindTag == other.kindTag &&
          fromNode == other.fromNode &&
          toNode == other.toNode &&
          aux == other.aux &&
          payloadBits == other.payloadBits;
}

/// FRB-friendly outcome.  The framework deliberately returns string
/// kind/reason tokens instead of an enum so the Dart side can map them
/// to localized strings without needing an FRB sealed class.
class TgfOutcome {
  /// One of "ongoing", "win", "draw", "abandoned".
  final String kind;

  /// Winner index when `kind == "win"`; -1 otherwise.
  final int winner;

  /// Stable English token, e.g. "loseFewerThanThree".
  final String reason;

  const TgfOutcome({
    required this.kind,
    required this.winner,
    required this.reason,
  });

  @override
  int get hashCode => kind.hashCode ^ winner.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfOutcome &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          winner == other.winner &&
          reason == other.reason;
}

/// FRB-friendly mirror of `GameStateSnapshot`.  The opaque payload is
/// emitted as a `Vec<u8>` (Dart `Uint8List`) so the Flutter side can
/// inspect game-specific blobs without knowing the C `[u8; 256]` layout.
class TgfSnapshot {
  final int sideToMove;
  final int phaseTag;
  final int moveNumber;
  final BigInt zobristKey;
  final Uint8List opaquePayload;

  const TgfSnapshot({
    required this.sideToMove,
    required this.phaseTag,
    required this.moveNumber,
    required this.zobristKey,
    required this.opaquePayload,
  });

  @override
  int get hashCode =>
      sideToMove.hashCode ^
      phaseTag.hashCode ^
      moveNumber.hashCode ^
      zobristKey.hashCode ^
      opaquePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfSnapshot &&
          runtimeType == other.runtimeType &&
          sideToMove == other.sideToMove &&
          phaseTag == other.phaseTag &&
          moveNumber == other.moveNumber &&
          zobristKey == other.zobristKey &&
          opaquePayload == other.opaquePayload;
}
