// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These functions are ignored because they are not marked as `pub`: `build_rules_default`, `from_action`, `from_outcome`, `from_snap`, `insert_kernel`, `into_action`, `map_kernel_error`, `mill_variant_for_handle`, `register_mill_variant`, `unregister_mill_variant`, `with_kernel`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Create a kernel for one of the built-in games using its default
/// variant options (`mill` ⇒ Nine Men's Morris, `othello` ⇒ standard
/// 8x8).  Returns the new session handle on success.
int tgfKernelCreate({required String gameId}) =>
    RustLib.instance.api.crateApiKernelTgfKernelCreate(gameId: gameId);

/// Create a Mill kernel with explicit variant options.  Use this once
/// the Flutter `RuleSettings` model is mapped through
/// `MillVariantOptionsMapper`.
int tgfKernelCreateMill({required MillVariantOptions variant}) =>
    RustLib.instance.api.crateApiKernelTgfKernelCreateMill(variant: variant);

/// Drop the session associated with `handle`.  Idempotent: invoking
/// twice is a no-op.
void tgfKernelDispose({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelDispose(handle: handle);

String tgfKernelGameId({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelGameId(handle: handle);

TgfSnapshot tgfKernelSnapshot({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSnapshot(handle: handle);

List<TgfAction> tgfKernelLegalActions({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelLegalActions(handle: handle);

TgfSnapshot tgfKernelApply({required int handle, required TgfAction action}) =>
    RustLib.instance.api.crateApiKernelTgfKernelApply(
      handle: handle,
      action: action,
    );

TgfSnapshot tgfKernelUndo({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelUndo(handle: handle);

TgfSnapshot tgfKernelRedo({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelRedo(handle: handle);

TgfOutcome tgfKernelOutcome({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelOutcome(handle: handle);

bool tgfKernelIsTerminal({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelIsTerminal(handle: handle);

int tgfKernelUndoDepth({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelUndoDepth(handle: handle);

int tgfKernelRedoDepth({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelRedoDepth(handle: handle);

/// PVS search over the kernel's **current** Mill position, using the same
/// variant options as [tgf_kernel_create_mill].
///
/// Streams the same [EngineEvent] sequence as [crate::api::simple::native_mill_search_events].
Stream<EngineEvent> tgfKernelMillSearchEvents({
  required int handle,
  required int depth,
}) => RustLib.instance.api.crateApiKernelTgfKernelMillSearchEvents(
  handle: handle,
  depth: depth,
);

/// Clear the board for setup-position editing.  Returns the empty snapshot.
/// Requires the handle to reference a Mill kernel.
TgfSnapshot tgfKernelSetupClear({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupClear(handle: handle);

/// Set or clear a piece during setup-position editing.
/// [owner]: 1 = first player, 2 = second player, other = clear.
TgfSnapshot tgfKernelSetupSetPiece({
  required int handle,
  required int node,
  required int owner,
}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupSetPiece(
      handle: handle,
      node: node,
      owner: owner,
    );

/// Set the side to move during setup-position editing.
/// [side]: 0 = first player, 1 = second player.
TgfSnapshot tgfKernelSetupSetSide({required int handle, required int side}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupSetSide(
      handle: handle,
      side: side,
    );

/// Finish setup-position editing and transition to a playable game state.
TgfSnapshot tgfKernelSetupFinish({required int handle}) =>
    RustLib.instance.api.crateApiKernelTgfKernelSetupFinish(handle: handle);

/// Mirror of `tgf_core::Action` with i32 fields so FRB can ship it as
/// trivial dart `int` types.  Conversion is `From`-symmetric.
class TgfAction {
  final int kindTag;
  final int fromNode;
  final int toNode;
  final int aux;
  final BigInt payloadBits;

  const TgfAction({
    required this.kindTag,
    required this.fromNode,
    required this.toNode,
    required this.aux,
    required this.payloadBits,
  });

  @override
  int get hashCode =>
      kindTag.hashCode ^
      fromNode.hashCode ^
      toNode.hashCode ^
      aux.hashCode ^
      payloadBits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfAction &&
          runtimeType == other.runtimeType &&
          kindTag == other.kindTag &&
          fromNode == other.fromNode &&
          toNode == other.toNode &&
          aux == other.aux &&
          payloadBits == other.payloadBits;
}

/// FRB-friendly outcome.  The framework deliberately returns string
/// kind/reason tokens instead of an enum so the Dart side can map them
/// to localized strings without needing an FRB sealed class.
class TgfOutcome {
  /// One of "ongoing", "win", "draw", "abandoned".
  final String kind;

  /// Winner index when `kind == "win"`; -1 otherwise.
  final int winner;

  /// Stable English token, e.g. "loseFewerThanThree".
  final String reason;

  const TgfOutcome({
    required this.kind,
    required this.winner,
    required this.reason,
  });

  @override
  int get hashCode => kind.hashCode ^ winner.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfOutcome &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          winner == other.winner &&
          reason == other.reason;
}

/// FRB-friendly mirror of `GameStateSnapshot`.  The opaque payload is
/// emitted as a `Vec<u8>` (Dart `Uint8List`) so the Flutter side can
/// inspect game-specific blobs without knowing the C `[u8; 256]` layout.
class TgfSnapshot {
  final int sideToMove;
  final int phaseTag;
  final int moveNumber;
  final BigInt zobristKey;
  final Uint8List opaquePayload;

  const TgfSnapshot({
    required this.sideToMove,
    required this.phaseTag,
    required this.moveNumber,
    required this.zobristKey,
    required this.opaquePayload,
  });

  @override
  int get hashCode =>
      sideToMove.hashCode ^
      phaseTag.hashCode ^
      moveNumber.hashCode ^
      zobristKey.hashCode ^
      opaquePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TgfSnapshot &&
          runtimeType == other.runtimeType &&
          sideToMove == other.sideToMove &&
          phaseTag == other.phaseTag &&
          moveNumber == other.moveNumber &&
          zobristKey == other.zobristKey &&
          opaquePayload == other.opaquePayload;
}
