// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'kernel.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

/// Create a Mill kernel with explicit variant options.  Use this once
/// the Flutter `RuleSettings` model is mapped through
/// `MillVariantOptionsMapper`.
int tgfKernelCreateMill({required MillVariantOptions variant}) => RustLib
    .instance
    .api
    .crateApiMillKernelTgfKernelCreateMill(variant: variant);

/// PVS search over the kernel's **current** Mill position, using the
/// same variant options as [tgf_kernel_create_mill].
///
/// Streams the same [EngineEvent] sequence as
/// [crate::api::simple::native_mill_search_events]: one `info` event
/// per IDS depth, then `bestMove` + `stopped`.
Stream<EngineEvent> tgfKernelMillSearchEvents({
  required int handle,
  required int depth,
}) => RustLib.instance.api.crateApiMillKernelTgfKernelMillSearchEvents(
  handle: handle,
  depth: depth,
);

/// Full-config search over the kernel's **current** Mill position.
///
/// Accepts a [`MillEngineConfig`] that controls algorithm, depth, time
/// limit and lazy-search behaviour.  Preferred over
/// [tgf_kernel_mill_search_events] for production use once the Flutter
/// side has migrated to the typed config.
Stream<EngineEvent> tgfKernelMillSearchEventsWithConfig({
  required int handle,
  required MillEngineConfig config,
}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelMillSearchEventsWithConfig(
      handle: handle,
      config: config,
    );

/// Clear the board associated with a Mill kernel handle and reset all
/// pieces, returning the fresh empty snapshot.  History and redo stacks
/// are cleared.
///
/// This is the entry point for the Flutter setup-position flow: call
/// `tgf_kernel_setup_clear` first, then `tgf_kernel_setup_set_piece` for
/// each piece, then `tgf_kernel_setup_finish` to transition to a
/// playable state.
TgfSnapshot tgfKernelSetupClear({required int handle}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelSetupClear(handle: handle);

/// Set or clear a single piece at `node` for a Mill kernel in setup
/// mode.
///
/// `owner`: `1` = first player (White), `2` = second player (Black),
/// any other value = clear the square.
///
/// Call `tgf_kernel_setup_clear` before the first `set_piece` to start
/// with a blank board, then `tgf_kernel_setup_finish` when editing is
/// complete.
TgfSnapshot tgfKernelSetupSetPiece({
  required int handle,
  required int node,
  required int owner,
}) => RustLib.instance.api.crateApiMillKernelTgfKernelSetupSetPiece(
  handle: handle,
  node: node,
  owner: owner,
);

/// Set the side to move for a Mill kernel in setup mode.
///
/// `side`: `0` = first player (White), `1` = second player (Black).
TgfSnapshot tgfKernelSetupSetSide({required int handle, required int side}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelSetupSetSide(
      handle: handle,
      side: side,
    );

/// Finish the setup-position editing flow.
///
/// Determines whether the resulting board is in placing or moving
/// phase based on whether any pieces remain in hand, recomputes
/// auxiliary fields, and replaces the kernel state.  After this call
/// the kernel can be used for normal play (legal actions, apply,
/// search).
TgfSnapshot tgfKernelSetupFinish({required int handle}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelSetupFinish(handle: handle);

/// Load a Mill board position from a FEN string.
///
/// Accepts node-id Mill FENs marked with `ids:nodes`, plus legacy square-id
/// FENs at import boundaries.  Returns the new snapshot on success, or an
/// error string on parse failure.
TgfSnapshot tgfKernelSetFromFen({required int handle, required String fen}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelSetFromFen(
      handle: handle,
      fen: fen,
    );

/// Analyse the kernel's **current** Mill position, returning one verdict per
/// legal move plus any detected trap moves.
///
/// Each move is evaluated against the perfect database (win/draw/loss + step
/// count) or, when the database has no entry, with a shallow heuristic search
/// (advantage/disadvantage).  When `trap_awareness` is set, aggressive moves
/// with a worse database verdict than an available alternative are reported in
/// [`MillAnalysisReport::traps`].  This backs the analysis overlay (the legacy
/// C++ `analyze` UCI command) without mutating the kernel state.
MillAnalysisReport tgfKernelMillPerfectDbAnalyze({
  required int handle,
  required bool trapAwareness,
}) => RustLib.instance.api.crateApiMillKernelTgfKernelMillPerfectDbAnalyze(
  handle: handle,
  trapAwareness: trapAwareness,
);

/// Export the current Mill kernel state as a FEN string.
String tgfKernelExportFen({required int handle}) =>
    RustLib.instance.api.crateApiMillKernelTgfKernelExportFen(handle: handle);
