// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `spawn_mill_engine_config_event_stream`, `spawn_mill_pvs_event_stream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Returns a greeting string confirming that the Rust → Dart bridge works.
/// Called from Dart as `tgfHelloWorld()` after `await RustLib.init()`.
String tgfHelloWorld() => RustLib.instance.api.crateApiSimpleTgfHelloWorld();

/// Returns the TGF Rust crate version string.
String tgfVersion() => RustLib.instance.api.crateApiSimpleTgfVersion();

/// Default Nine Men's Morris variant options.
MillVariantOptions nativeMillDefaultVariantOptions() =>
    RustLib.instance.api.crateApiSimpleNativeMillDefaultVariantOptions();

/// Number of legal actions from the Rust-native Othello initial position.
int nativeOthelloInitialLegalCount() =>
    RustLib.instance.api.crateApiSimpleNativeOthelloInitialLegalCount();

/// Run the generic Rust Searcher<OthelloGame> for one ply and return the
/// selected destination node.
int nativeOthelloSearchDepthOneBestToNode() =>
    RustLib.instance.api.crateApiSimpleNativeOthelloSearchDepthOneBestToNode();

/// Initialize the Mill perfect database directory from `path`.
/// The directory may contain `std`, `lask`, and/or `mora` database files; the
/// active Mill rules select the concrete variant at query time.
bool millPerfectDbInit({required String path}) =>
    RustLib.instance.api.crateApiSimpleMillPerfectDbInit(path: path);

/// Inspect the Mill perfect database directory without initializing it.
MillPerfectDatabaseStatus millPerfectDbStatus({required String path}) =>
    RustLib.instance.api.crateApiSimpleMillPerfectDbStatus(path: path);

/// Release perfect-database resources for the current process.
void millPerfectDbDeinit() =>
    RustLib.instance.api.crateApiSimpleMillPerfectDbDeinit();

/// Initialize a read-only human-game SQLite database.
bool millHumanDbInit({required String path}) =>
    RustLib.instance.api.crateApiSimpleMillHumanDbInit(path: path);

/// Inspect a human-game SQLite database without requiring a query.
MillHumanDatabaseStatus millHumanDbStatus({required String path}) =>
    RustLib.instance.api.crateApiSimpleMillHumanDbStatus(path: path);

/// Query candidate moves for a Mill FEN from the initialized Human Database.
MillHumanDatabaseQuery millHumanDbQuery({
  required String fen,
  required int maxMoves,
  required int minSamples,
}) => RustLib.instance.api.crateApiSimpleMillHumanDbQuery(
  fen: fen,
  maxMoves: maxMoves,
  minSamples: minSamples,
);

/// Release Human Database resources for the current process.
void millHumanDbDeinit() =>
    RustLib.instance.api.crateApiSimpleMillHumanDbDeinit();

/// Return the Rust-native standard 24-point Mill topology.
///
/// This is the single source of truth for Mill board geometry.  The Dart
/// shell converts this blob into its existing BoardGeometry value object.
///
/// Generic callers that already hold a kernel handle should prefer
/// [`tgf_kernel_topology`] instead — it routes through the same
/// `BoardTopology` trait every game implements, so it works for
/// Othello / Checkers / future games without an extra entry point.
TopologyBlob nativeMillTopology() =>
    RustLib.instance.api.crateApiSimpleNativeMillTopology();

/// Backwards-compatible alias for [`native_mill_topology`].  Deprecated
/// because the name implies kernel awareness while the implementation
/// always returns the default Mill topology regardless of any kernel
/// state.  Will be removed one release after every Dart call site
/// migrates.
TopologyBlob kernelTopology() =>
    RustLib.instance.api.crateApiSimpleKernelTopology();

/// Game-neutral topology accessor: routes the call through the kernel
/// session's `BoardTopology` so each game ships its own geometry
/// without needing a bespoke FRB entry.  The `square` field of every
/// emitted [`TopologyPoint`] mirrors the node id for games that have
/// no separate legacy square space (i.e. everything except Mill);
/// Mill's square space is exposed through [`native_mill_topology`].
TopologyBlob tgfKernelTopology({required int handle}) =>
    RustLib.instance.api.crateApiSimpleTgfKernelTopology(handle: handle);

/// Game-neutral player-info accessor: routes the call through the
/// kernel session's `GameRules::multi_player_info` so each game ships
/// its own player layout without a bespoke FRB entry.  The shell uses
/// this to decide turn-order indicators, team colour palettes, and
/// `WinTeam` rendering paths at session start.
PlayerInfoBlob tgfKernelPlayerInfo({required int handle}) =>
    RustLib.instance.api.crateApiSimpleTgfKernelPlayerInfo(handle: handle);

/// Number of legal actions from a fresh Rust-native Mill initial position.
/// This should match the mature C++ engine at depth 1: 24 placing moves.
int nativeMillInitialLegalCount() =>
    RustLib.instance.api.crateApiSimpleNativeMillInitialLegalCount();

/// Opening legal action count for an explicit variant option set.
int nativeMillInitialLegalCountForVariant({
  required MillVariantOptions variant,
}) => RustLib.instance.api.crateApiSimpleNativeMillInitialLegalCountForVariant(
  variant: variant,
);

/// Apply the first Rust-native place action and return the side-to-move tag.
/// This is a small typed smoke-check for the native MillRules implementation.
int nativeMillApplyFirstPlaceSideToMove() =>
    RustLib.instance.api.crateApiSimpleNativeMillApplyFirstPlaceSideToMove();

/// Play the canonical a7-d7-g7 mill formation sequence and return how many
/// native Rust remove actions are generated.
int nativeMillMillSequenceRemoveCount() =>
    RustLib.instance.api.crateApiSimpleNativeMillMillSequenceRemoveCount();

/// Smoke-check: moving-phase move that forms a mill generates remove actions.
int nativeMillMovingMillRemoveCount() =>
    RustLib.instance.api.crateApiSimpleNativeMillMovingMillRemoveCount();

/// Smoke-check: removing below three pieces ends the game with White as winner.
int nativeMillRemovalBelowThreeWinner() =>
    RustLib.instance.api.crateApiSimpleNativeMillRemovalBelowThreeWinner();

/// Run the Rust generic Searcher<MillGame> for one ply and return the best
/// destination node. This is a smoke-check for the monomorphised search path.
int nativeMillSearchDepthOneBestToNode() =>
    RustLib.instance.api.crateApiSimpleNativeMillSearchDepthOneBestToNode();

/// Run the Rust generic PVS path for one ply and return the best destination.
int nativeMillPvsDepthOneBestToNode() =>
    RustLib.instance.api.crateApiSimpleNativeMillPvsDepthOneBestToNode();

/// Run deterministic random-search with a caller-supplied seed.
int nativeMillRandomBestToNode({required BigInt seed}) =>
    RustLib.instance.api.crateApiSimpleNativeMillRandomBestToNode(seed: seed);

/// Run the Rust generic MCTS path and return the selected destination node.
int nativeMillMctsBestToNode({
  required BigInt seed,
  required int iterationsPerMove,
}) => RustLib.instance.api.crateApiSimpleNativeMillMctsBestToNode(
  seed: seed,
  iterationsPerMove: iterationsPerMove,
);

/// Smoke-check that the Rust searcher honours a zero-millisecond time limit.
bool nativeMillSearchZeroTimeLimitAborts() =>
    RustLib.instance.api.crateApiSimpleNativeMillSearchZeroTimeLimitAborts();

/// Async search event stream rooted at the Mill initial position.
///
/// Spawns a worker thread, runs the native Rust `Searcher<MillGame>`, and
/// emits Ready / Info / BestMove / Stopped.  Used as a smoke-check entry
/// point during development; production paths go through
/// `tgf_kernel_mill_search_events*` instead.
Stream<EngineEvent> nativeMillSearchEvents({required int depth}) =>
    RustLib.instance.api.crateApiSimpleNativeMillSearchEvents(depth: depth);

/// Request that the currently running native Rust search stops.
///
/// Returns false when no native search worker is active.
bool nativeMillSearchStop() =>
    RustLib.instance.api.crateApiSimpleNativeMillSearchStop();

class CaptureRuleConfig {
  final bool enabled;
  final bool onSquareEdges;
  final bool onCrossLines;
  final bool onDiagonalLines;
  final bool inPlacingPhase;
  final bool inMovingPhase;
  final bool onlyAvailableWhenOwnPiecesLeq3;

  const CaptureRuleConfig({
    required this.enabled,
    required this.onSquareEdges,
    required this.onCrossLines,
    required this.onDiagonalLines,
    required this.inPlacingPhase,
    required this.inMovingPhase,
    required this.onlyAvailableWhenOwnPiecesLeq3,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      onSquareEdges.hashCode ^
      onCrossLines.hashCode ^
      onDiagonalLines.hashCode ^
      inPlacingPhase.hashCode ^
      inMovingPhase.hashCode ^
      onlyAvailableWhenOwnPiecesLeq3.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureRuleConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          onSquareEdges == other.onSquareEdges &&
          onCrossLines == other.onCrossLines &&
          onDiagonalLines == other.onDiagonalLines &&
          inPlacingPhase == other.inPlacingPhase &&
          inMovingPhase == other.inMovingPhase &&
          onlyAvailableWhenOwnPiecesLeq3 ==
              other.onlyAvailableWhenOwnPiecesLeq3;
}

/// Game-neutral engine event POD shipped over the FRB stream API.
///
/// This struct is the wire format Dart sees; the helper constructors and
/// spawn-and-emit logic live in `crate::engine_event` and
/// `crate::games::*` respectively so this module stays a thin ABI shim.
class EngineEvent {
  final String kind;
  final int depth;
  final int score;
  final BigInt nodes;
  final int toNode;

  /// For bestMove events: the full notation move string ("a4", "a1-a4",
  /// "xa4" for Mill) plus auxiliary annotations such as `rawScore=N`.
  /// For error events: the human-readable error message.  The Dart side
  /// parses this loosely; new fields ride along here to avoid codegen.
  final String reason;

  const EngineEvent({
    required this.kind,
    required this.depth,
    required this.score,
    required this.nodes,
    required this.toNode,
    required this.reason,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      depth.hashCode ^
      score.hashCode ^
      nodes.hashCode ^
      toNode.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          depth == other.depth &&
          score == other.score &&
          nodes == other.nodes &&
          toNode == other.toNode &&
          reason == other.reason;
}

/// Full analysis result for a position: one verdict per legal move plus the
/// detected trap moves (empty unless trap detection ran and found any).
class MillAnalysisReport {
  /// One verdict per legal move.
  final List<MillMoveAnalysis> moves;

  /// Notation tokens of moves flagged as traps.
  final List<String> traps;

  const MillAnalysisReport({required this.moves, required this.traps});

  @override
  int get hashCode => moves.hashCode ^ traps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillAnalysisReport &&
          runtimeType == other.runtimeType &&
          moves == other.moves &&
          traps == other.traps;
}

enum MillBoardFullAction {
  firstPlayerLose,
  firstAndSecondPlayerRemovePiece,
  secondAndFirstPlayerRemovePiece,
  sideToMoveRemovePiece,
  agreeToDraw,
}

/// Engine configuration passed from Flutter to Rust for every search.
/// Consolidates all user-facing AI behaviour knobs that were previously
/// sent as UCI `setoption` strings via the C++ MethodChannel.
class MillEngineConfig {
  /// Search algorithm.  Default: MTD(f) (P2-A).
  final MillSearchAlgorithm algorithm;

  /// AI search depth (0 → auto via drawOnHumanExperience table on Dart side).
  final int depth;

  /// Time limit in milliseconds (0 = unlimited; depth drives termination).
  final int moveTimeMs;

  /// When true, apply the `AiIsLazy` depth adjustment from master
  /// `search_engine.cpp`: if the previous best value suggests the position
  /// is winning by more than 1 piece, cap origin_depth to 1; otherwise
  /// keep it (P2-G).
  final bool aiIsLazy;

  /// The best value from the previous turn's search, used by `ai_is_lazy`
  /// logic. Mirrors master's `bestvalue` input to `executeSearch` (P2-G).
  /// Flutter should back-fill this from the last `bestMove` event score.
  final int lastBestValue;

  /// SkillLevel (0-30): controls MCTS iteration count (skill_level * 2048)
  /// matching master `SkillLevel * ITERATIONS_PER_SKILL_LEVEL` (P2-F/P2-I).
  final int skillLevel;

  /// When true, query the perfect database after search and prefer its move
  /// when the active rule variant has matching database assets.
  final bool usePerfectDatabase;

  /// When true, randomise the order of equally-ranked root moves so the AI
  /// does not always play the same line (master `Shuffling` UCI option).
  /// Flutter forwards `GeneralSettings.shufflingEnabled`; disable for
  /// deterministic play.  Also drives the per-rollout move ordering in the
  /// MCTS path.
  final bool shuffling;

  /// Enable multi-threaded native search where supported.  Multi-threading is
  /// ignored when `shuffling` is false so deterministic play still returns a
  /// stable best move for a fixed position.
  final bool useLazySmp;

  /// Requested worker/thread count for multi-threaded search.  The engine
  /// clamps the value to a conservative range.
  final int engineThreads;

  /// Requested MultiPV line count.  `1` keeps the legacy single-line stream.
  final int multiPv;

  const MillEngineConfig({
    required this.algorithm,
    required this.depth,
    required this.moveTimeMs,
    required this.aiIsLazy,
    required this.lastBestValue,
    required this.skillLevel,
    required this.usePerfectDatabase,
    required this.shuffling,
    required this.useLazySmp,
    required this.engineThreads,
    required this.multiPv,
  });

  static Future<MillEngineConfig> default_() =>
      RustLib.instance.api.crateApiSimpleMillEngineConfigDefault();

  @override
  int get hashCode =>
      algorithm.hashCode ^
      depth.hashCode ^
      moveTimeMs.hashCode ^
      aiIsLazy.hashCode ^
      lastBestValue.hashCode ^
      skillLevel.hashCode ^
      usePerfectDatabase.hashCode ^
      shuffling.hashCode ^
      useLazySmp.hashCode ^
      engineThreads.hashCode ^
      multiPv.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillEngineConfig &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          depth == other.depth &&
          moveTimeMs == other.moveTimeMs &&
          aiIsLazy == other.aiIsLazy &&
          lastBestValue == other.lastBestValue &&
          skillLevel == other.skillLevel &&
          usePerfectDatabase == other.usePerfectDatabase &&
          shuffling == other.shuffling &&
          useLazySmp == other.useLazySmp &&
          engineThreads == other.engineThreads &&
          multiPv == other.multiPv;
}

enum MillFormationActionInPlacingPhase {
  removeOpponentsPieceFromBoard,
  removeOpponentsPieceFromHandThenOpponentsTurn,
  removeOpponentsPieceFromHandThenYourTurn,
  opponentRemovesOwnPiece,
  markAndDelayRemovingPieces,
  removalBasedOnMillCounts,
}

/// One Human Database move candidate mapped back into the current board orientation.
class MillHumanDatabaseMove {
  /// Move notation (`"a4"`, `"a1-a4"`, or complete `"a4xb6"`).
  final String notation;
  final int wins;
  final int losses;
  final int draws;
  final int total;

  /// Raw human-game win percentage for the side to move.
  final double winPct;

  /// Confidence-weighted delta in the range [-0.5, 0.5].
  final double scoreDelta;

  const MillHumanDatabaseMove({
    required this.notation,
    required this.wins,
    required this.losses,
    required this.draws,
    required this.total,
    required this.winPct,
    required this.scoreDelta,
  });

  @override
  int get hashCode =>
      notation.hashCode ^
      wins.hashCode ^
      losses.hashCode ^
      draws.hashCode ^
      total.hashCode ^
      winPct.hashCode ^
      scoreDelta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillHumanDatabaseMove &&
          runtimeType == other.runtimeType &&
          notation == other.notation &&
          wins == other.wins &&
          losses == other.losses &&
          draws == other.draws &&
          total == other.total &&
          winPct == other.winPct &&
          scoreDelta == other.scoreDelta;
}

/// Human Database query result for the current Mill FEN.
class MillHumanDatabaseQuery {
  final bool available;
  final String stateKey;
  final String error;
  final List<MillHumanDatabaseMove> moves;

  const MillHumanDatabaseQuery({
    required this.available,
    required this.stateKey,
    required this.error,
    required this.moves,
  });

  @override
  int get hashCode =>
      available.hashCode ^ stateKey.hashCode ^ error.hashCode ^ moves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillHumanDatabaseQuery &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          stateKey == other.stateKey &&
          error == other.error &&
          moves == other.moves;
}

/// Runtime status for an optional human-game SQLite database.
class MillHumanDatabaseStatus {
  /// Whether the SQLite file could be opened and passed schema checks.
  final bool readable;

  /// Whether this exact file is currently initialized for queries.
  final bool initialized;

  /// Read/schema error when `readable` is false; empty otherwise.
  final String error;

  /// Source database schema version from the metadata table.
  final String schemaVersion;

  /// Source database build date from the metadata table.
  final String buildDate;

  /// Number of games indexed by the database builder.
  final int totalGames;

  /// Number of indexed canonical positions.
  final int positionCount;

  /// Number of indexed move rows.
  final int moveCount;

  const MillHumanDatabaseStatus({
    required this.readable,
    required this.initialized,
    required this.error,
    required this.schemaVersion,
    required this.buildDate,
    required this.totalGames,
    required this.positionCount,
    required this.moveCount,
  });

  @override
  int get hashCode =>
      readable.hashCode ^
      initialized.hashCode ^
      error.hashCode ^
      schemaVersion.hashCode ^
      buildDate.hashCode ^
      totalGames.hashCode ^
      positionCount.hashCode ^
      moveCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillHumanDatabaseStatus &&
          runtimeType == other.runtimeType &&
          readable == other.readable &&
          initialized == other.initialized &&
          error == other.error &&
          schemaVersion == other.schemaVersion &&
          buildDate == other.buildDate &&
          totalGames == other.totalGames &&
          positionCount == other.positionCount &&
          moveCount == other.moveCount;
}

/// Perfect-database verdict for one legal move, used by the analysis overlay.
///
/// `value` and `outcome` are expressed from the perspective of the side that
/// is to move in the analysed position (`"win"` / `"draw"` / `"loss"` and
/// `1` / `0` / `-1`).  `steps` is the distance-to-conversion step count, or a
/// negative value when the database does not expose one.
class MillMoveAnalysis {
  /// Mill UCI notation token (`"a4"`, `"a1-a4"`, `"xg7"`).
  final String mv;

  /// `"win"`, `"draw"` or `"loss"` for the analysing side.
  final String outcome;

  /// Win/draw/loss value for the analysing side (1 / 0 / -1).
  final int value;

  /// Distance-to-conversion step count; negative when unavailable.
  final int steps;

  const MillMoveAnalysis({
    required this.mv,
    required this.outcome,
    required this.value,
    required this.steps,
  });

  @override
  int get hashCode =>
      mv.hashCode ^ outcome.hashCode ^ value.hashCode ^ steps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillMoveAnalysis &&
          runtimeType == other.runtimeType &&
          mv == other.mv &&
          outcome == other.outcome &&
          value == other.value &&
          steps == other.steps;
}

/// Perfect Database directory status used for setup diagnostics.
class MillPerfectDatabaseStatus {
  /// Whether the directory could be read and parsed.
  final bool readable;

  /// Parse/read error message when `readable` is false; empty otherwise.
  final String error;

  /// Whether any supported `.secval` metadata was found.
  final bool hasMetadata;

  /// Whether any supported variant has at least one available `.sec2` file.
  final bool hasAvailableSectors;

  /// Status for every supported variant found in the directory.
  final List<MillPerfectDatabaseVariantStatus> variants;

  const MillPerfectDatabaseStatus({
    required this.readable,
    required this.error,
    required this.hasMetadata,
    required this.hasAvailableSectors,
    required this.variants,
  });

  @override
  int get hashCode =>
      readable.hashCode ^
      error.hashCode ^
      hasMetadata.hashCode ^
      hasAvailableSectors.hashCode ^
      variants.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillPerfectDatabaseStatus &&
          runtimeType == other.runtimeType &&
          readable == other.readable &&
          error == other.error &&
          hasMetadata == other.hasMetadata &&
          hasAvailableSectors == other.hasAvailableSectors &&
          variants == other.variants;
}

/// Availability summary for one Perfect Database variant in a directory.
class MillPerfectDatabaseVariantStatus {
  /// Legacy database variant name: `std`, `lask`, or `mora`.
  final String name;

  /// Piece count associated with the variant.
  final int pieceCount;

  /// Number of sector ids listed by the `.secval` file.
  final int sectorCount;

  /// Number of listed sectors whose `.sec2` files are present.
  final int availableSectorCount;

  const MillPerfectDatabaseVariantStatus({
    required this.name,
    required this.pieceCount,
    required this.sectorCount,
    required this.availableSectorCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      pieceCount.hashCode ^
      sectorCount.hashCode ^
      availableSectorCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillPerfectDatabaseVariantStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          pieceCount == other.pieceCount &&
          sectorCount == other.sectorCount &&
          availableSectorCount == other.availableSectorCount;
}

/// Search algorithm selector exposed to Flutter.
/// Values match C++ `Algorithm` enum in `src/types.h` and Dart's
/// `SearchAlgorithm` enum in `general_settings.dart`.
enum MillSearchAlgorithm {
  alphaBeta,
  pvs,
  mtdf,
  mcts,
  random;

  static Future<MillSearchAlgorithm> default_() =>
      RustLib.instance.api.crateApiSimpleMillSearchAlgorithmDefault();
}

/// Public FRB DTO for Mill variant options. It mirrors
/// `tgf_mill::rules::MillVariantOptions`; new rule flags should be added here
/// whenever the Rust rules crate grows them.
class MillVariantOptions {
  final int pieceCount;
  final int flyPieceCount;
  final int piecesAtLeastCount;
  final bool mayFly;
  final bool hasDiagonalLines;
  final MillFormationActionInPlacingPhase millFormationActionInPlacingPhase;
  final bool mayRemoveFromMillsAlways;
  final bool mayRemoveMultiple;
  final int nMoveRule;
  final int endgameNMoveRule;
  final bool mayMoveInPlacingPhase;
  final bool isDefenderMoveFirst;
  final bool restrictRepeatedMillsFormation;
  final bool oneTimeUseMill;
  final bool stopPlacingWhenTwoEmptySquares;
  final MillBoardFullAction boardFullAction;
  final bool threefoldRepetitionRule;
  final CaptureRuleConfig custodianCapture;
  final CaptureRuleConfig interventionCapture;
  final CaptureRuleConfig leapCapture;
  final StalemateAction stalemateAction;

  /// Mirror of `gameOptions.getConsiderMobility()` from the legacy C++
  /// engine.  Drives [`MillEvaluator`] mobility scoring.  Default
  /// `true` matches the C++ side.
  final bool considerMobility;

  /// Mirror of `gameOptions.getFocusOnBlockingPaths()`: when set, the
  /// static evaluator drops the material term so the search prioritises
  /// blocking lines.  Default `false`.
  final bool focusOnBlockingPaths;

  const MillVariantOptions({
    required this.pieceCount,
    required this.flyPieceCount,
    required this.piecesAtLeastCount,
    required this.mayFly,
    required this.hasDiagonalLines,
    required this.millFormationActionInPlacingPhase,
    required this.mayRemoveFromMillsAlways,
    required this.mayRemoveMultiple,
    required this.nMoveRule,
    required this.endgameNMoveRule,
    required this.mayMoveInPlacingPhase,
    required this.isDefenderMoveFirst,
    required this.restrictRepeatedMillsFormation,
    required this.oneTimeUseMill,
    required this.stopPlacingWhenTwoEmptySquares,
    required this.boardFullAction,
    required this.threefoldRepetitionRule,
    required this.custodianCapture,
    required this.interventionCapture,
    required this.leapCapture,
    required this.stalemateAction,
    required this.considerMobility,
    required this.focusOnBlockingPaths,
  });

  @override
  int get hashCode =>
      pieceCount.hashCode ^
      flyPieceCount.hashCode ^
      piecesAtLeastCount.hashCode ^
      mayFly.hashCode ^
      hasDiagonalLines.hashCode ^
      millFormationActionInPlacingPhase.hashCode ^
      mayRemoveFromMillsAlways.hashCode ^
      mayRemoveMultiple.hashCode ^
      nMoveRule.hashCode ^
      endgameNMoveRule.hashCode ^
      mayMoveInPlacingPhase.hashCode ^
      isDefenderMoveFirst.hashCode ^
      restrictRepeatedMillsFormation.hashCode ^
      oneTimeUseMill.hashCode ^
      stopPlacingWhenTwoEmptySquares.hashCode ^
      boardFullAction.hashCode ^
      threefoldRepetitionRule.hashCode ^
      custodianCapture.hashCode ^
      interventionCapture.hashCode ^
      leapCapture.hashCode ^
      stalemateAction.hashCode ^
      considerMobility.hashCode ^
      focusOnBlockingPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MillVariantOptions &&
          runtimeType == other.runtimeType &&
          pieceCount == other.pieceCount &&
          flyPieceCount == other.flyPieceCount &&
          piecesAtLeastCount == other.piecesAtLeastCount &&
          mayFly == other.mayFly &&
          hasDiagonalLines == other.hasDiagonalLines &&
          millFormationActionInPlacingPhase ==
              other.millFormationActionInPlacingPhase &&
          mayRemoveFromMillsAlways == other.mayRemoveFromMillsAlways &&
          mayRemoveMultiple == other.mayRemoveMultiple &&
          nMoveRule == other.nMoveRule &&
          endgameNMoveRule == other.endgameNMoveRule &&
          mayMoveInPlacingPhase == other.mayMoveInPlacingPhase &&
          isDefenderMoveFirst == other.isDefenderMoveFirst &&
          restrictRepeatedMillsFormation ==
              other.restrictRepeatedMillsFormation &&
          oneTimeUseMill == other.oneTimeUseMill &&
          stopPlacingWhenTwoEmptySquares ==
              other.stopPlacingWhenTwoEmptySquares &&
          boardFullAction == other.boardFullAction &&
          threefoldRepetitionRule == other.threefoldRepetitionRule &&
          custodianCapture == other.custodianCapture &&
          interventionCapture == other.interventionCapture &&
          leapCapture == other.leapCapture &&
          stalemateAction == other.stalemateAction &&
          considerMobility == other.considerMobility &&
          focusOnBlockingPaths == other.focusOnBlockingPaths;
}

/// Multi-player metadata mirroring [`tgf_core::MultiPlayerInfo`] for
/// the FRB boundary.  Two-player games (Mill, Othello) emit
/// `player_count = 2` and the standard sequential turn order; team
/// games (军棋, Halma) populate `team_of` to advertise alliances so
/// the shell can render team UI / colour palettes accordingly.
class PlayerInfoBlob {
  final int playerCount;
  final Uint8List teamOf;
  final Uint8List turnOrder;

  const PlayerInfoBlob({
    required this.playerCount,
    required this.teamOf,
    required this.turnOrder,
  });

  @override
  int get hashCode =>
      playerCount.hashCode ^ teamOf.hashCode ^ turnOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerInfoBlob &&
          runtimeType == other.runtimeType &&
          playerCount == other.playerCount &&
          teamOf == other.teamOf &&
          turnOrder == other.turnOrder;
}

enum StalemateAction {
  endWithStalemateLoss,
  changeSideToMove,
  removeOpponentsPieceAndMakeNextMove,
  removeOpponentsPieceAndChangeSideToMove,
  endWithStalemateDraw,
  bothPlayersRemoveOpponentsPiece,
}

class TopologyBlob {
  final String name;
  final List<TopologyPoint> points;
  final List<TopologyEdge> edges;
  final List<Uint16List> lineGroups;

  const TopologyBlob({
    required this.name,
    required this.points,
    required this.edges,
    required this.lineGroups,
  });

  @override
  int get hashCode =>
      name.hashCode ^ points.hashCode ^ edges.hashCode ^ lineGroups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopologyBlob &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          points == other.points &&
          edges == other.edges &&
          lineGroups == other.lineGroups;
}

class TopologyEdge {
  final int a;
  final int b;

  /// Per-game edge classification (see `tgf_core::Edge::kind_tag`).
  /// `0` = default/generic.  Used by games with multi-modal edges
  /// (军棋: railroad vs ordinary connections).
  final int kindTag;

  const TopologyEdge({required this.a, required this.b, required this.kindTag});

  @override
  int get hashCode => a.hashCode ^ b.hashCode ^ kindTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopologyEdge &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          kindTag == other.kindTag;
}

class TopologyPoint {
  final int id;
  final int square;
  final String label;
  final double x;
  final double y;

  const TopologyPoint({
    required this.id,
    required this.square,
    required this.label,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode =>
      id.hashCode ^ square.hashCode ^ label.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopologyPoint &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          square == other.square &&
          label == other.label &&
          x == other.x &&
          y == other.y;
}
