// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Returns a greeting string confirming that the Rust → Dart bridge works.
/// Called from Dart as `tgfHelloWorld()` after `await RustLib.init()`.
String tgfHelloWorld() => RustLib.instance.api.crateApiSimpleTgfHelloWorld();

/// Returns the TGF Rust crate version string.
String tgfVersion() => RustLib.instance.api.crateApiSimpleTgfVersion();
