// SPDX-License-Identifier: AGPL-3.0-or-later
// tgf-frb – flutter_rust_bridge v2 public API surface.
//
// This crate is the ONLY point of contact between Dart and Rust.
// FRB v2 auto-generates the Dart bindings from `#[frb]` annotations
// applied to functions inside `pub mod api`.
//
// Internal organisation (NOT scanned by FRB codegen):
//
//   - `engine_event`        — game-neutral PVS / MTD(f) / MCTS event
//                             stream helpers used by every search adapter.
//   - `session_registry`    — game-neutral kernel + per-handle extras map.
//   - `games::mill`         — Mill-specific FRB DTOs, action codecs,
//                             variant-extras helpers, and the spawn
//                             helpers powering the Mill search event
//                             stream.
//   - `games::othello`      — Othello-specific helpers for the FRB layer.
//
// Public FRB entry points still live under `api/` so the generated Dart
// import paths (`lib/src/rust/api/*.dart`) stay backwards compatible.

// Generated by `flutter_rust_bridge_codegen generate` – do not edit.
mod frb_generated;

mod engine_event;
mod game_registry;
mod games;
mod session_registry;

pub mod api;
