// SPDX-License-Identifier: GPL-3.0-or-later
// tgf-frb – flutter_rust_bridge v2 public API surface.
//
// This crate is the ONLY point of contact between Dart and Rust.
// FRB v2 auto-generates the Dart bindings from `#[frb]` annotations.
//
// Module structure mirrors the generated Dart file names:
//   src/api/simple.rs → lib/src/rust/api/simple.dart

// Generated by `flutter_rust_bridge_codegen generate` – do not edit.
mod frb_generated;

pub mod api;
