// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2019-2025 The Sanmill developers (see AUTHORS file)

// puzzle_adapters.dart
//
// Hive type adapters for puzzle models

library;

import 'package:hive_ce_flutter/hive_flutter.dart';

import 'puzzle_models.dart';

/// Type ids reserved for puzzle-related Hive adapters.
const int puzzleInfoTypeId = 30;
const int puzzleProgressTypeId = 31;
const int puzzleSettingsTypeId = 32;
const int puzzleDifficultyTypeId = 33;
const int puzzleCategoryTypeId = 34;

// Enums need manual adapters

/// Adapter for PuzzleDifficulty enum
class PuzzleDifficultyAdapter extends TypeAdapter<PuzzleDifficulty> {
  @override
  final int typeId = puzzleDifficultyTypeId;

  @override
  PuzzleDifficulty read(BinaryReader reader) {
    return PuzzleDifficulty.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, PuzzleDifficulty obj) {
    writer.writeByte(obj.index);
  }
}

/// Adapter for PuzzleCategory enum
class PuzzleCategoryAdapter extends TypeAdapter<PuzzleCategory> {
  @override
  final int typeId = puzzleCategoryTypeId;

  @override
  PuzzleCategory read(BinaryReader reader) {
    return PuzzleCategory.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, PuzzleCategory obj) {
    writer.writeByte(obj.index);
  }
}

// Classes will use generated adapters (PuzzleInfo, PuzzleProgress, PuzzleSettings)
// These are annotated with @HiveType and will be generated by build_runner
