#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2019-2026 The Sanmill developers (see AUTHORS file)
"""Concatenate master:src/ engine C++ sources into a single file.

Companion to ``dump_rust_sources.py``: produces a single text blob the
reviewer can diff against the Rust port.

Excludes (from the master tree, not the working copy):

  * ``src/perfect/`` (the Perfect Database is intentionally out of
    scope for the Rust port);
  * ``src/ui/`` (Qt/Flutter front-end, not engine logic);
  * non-C++ files (Makefile, .gitignore, etc.) — we only collect
    ``.cpp / .h / .hpp / .cc / .cxx`` extensions.

The output is written to ``master_cxx_combined.txt`` in the repo root
and is intentionally listed in ``.gitignore``.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "master_cxx_combined.txt"

# Subdirectory names anywhere in the path that disqualify a file.
EXCLUDE_DIR_PARTS = {"perfect", "ui"}

INCLUDE_EXT = {".cpp", ".h", ".hpp", ".cc", ".cxx", ".hh"}

MASTER_REF = "master"


def list_master_files() -> List[Path]:
    proc = subprocess.run(
        [
            "git",
            "ls-tree",
            "-r",
            "--name-only",
            MASTER_REF,
            "--",
            "src/",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    files: List[Path] = []
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        path = Path(line)
        if path.suffix.lower() not in INCLUDE_EXT:
            continue
        if any(part in EXCLUDE_DIR_PARTS for part in path.parts):
            continue
        files.append(path)
    files.sort()
    return files


def read_master_blob(path: Path) -> str:
    proc = subprocess.run(
        ["git", "show", f"{MASTER_REF}:{path.as_posix()}"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return proc.stdout


def main() -> int:
    try:
        subprocess.run(
            ["git", "rev-parse", "--verify", MASTER_REF],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        print(
            f"error: git could not resolve '{MASTER_REF}' reference: {exc.stderr}",
            file=sys.stderr,
        )
        return 2

    files = list_master_files()
    total_bytes = 0
    with OUT.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("// =====================================================\n")
        fh.write("// Generated by scripts/dump_master_cxx_sources.py\n")
        fh.write(
            "// Concatenated C++ sources from master:src/, excluding\n"
            "// src/perfect/ (Perfect Database) and src/ui/ (Qt/Flutter\n"
            "// front-ends).\n"
        )
        fh.write(f"// Files: {len(files)} ({MASTER_REF}:src/)\n")
        fh.write("// =====================================================\n\n")
        for path in files:
            content = read_master_blob(path)
            fh.write(f"\n// ===== {MASTER_REF}:{path.as_posix()} =====\n")
            fh.write(content)
            if not content.endswith("\n"):
                fh.write("\n")
            total_bytes += len(content)
    size = OUT.stat().st_size
    print(
        f"Wrote {OUT.relative_to(ROOT)} "
        f"({size:,} bytes on disk; ~{total_bytes:,} bytes of source; "
        f"{len(files)} files)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
