name: CUI on Windows

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make gcc-g++

      # Build
      - name: Build CUI
        run: cd src; make -j build ARCH=x86-64

      # Archive apk
      - name: Archive CUI
        uses: actions/upload-artifact@v2
        with:
          name: sanmill-for-cygwin
          path: src/sanmill.exe
