name: Dart Analyze

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Dart Analyze
    container:
      image:  google/dart:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
    - run: bash -x ./flutter-init.sh
    - name: Analyze Flutter
      uses: zgosalvez/github-actions-analyze-dart@v1.6.1
      with:
        fail-on-warnings: true
        working-directory: src/ui/flutter_app
        analysis-options-file: analysis_options.yaml
