name: Dart Analyze

on:
  push:
    paths:
      - 'src/ui/flutter_app/**'

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Lint flutter code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
    - run: bash -x ./flutter-init.sh
    - run: cp -f ./src/ui/flutter_app/analysis_options.yaml ./
    - name: Analyze Flutter
      uses: ValentinVignal/action-dart-analyze@v0.11
      with:
        fail-on: 'format'
        working-directory: src/ui/flutter_app
