name: Qt on Windows

on:
  push:
    branches: [master, dev]
    paths:
      - 'src/ui/qt/**'
  pull_request:
    types: [review_requested, ready_for_review]
    paths:
      - 'src/ui/qt/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup VS
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          modules: 'qtcore qtwgui qtmultimedia'
          cached: 'false'
          setup-python: 'true'
          tools: 'tools_cmake,3.24.2,qt.tools.cmake.win64'
          set-env: 'false'
          tools-only: 'false'
          aqtversion: '==1.2.5'
          py7zrversion: '==0.16.1'
          extra: '--external 7z'

      - name: Build Qt with CMake
        run: |
          cd src/ui/qt
          cmake . -DCMAKE_PREFIX_PATH="D:\\a\\Sanmill\\Qt\\5.15.2\\msvc2019_64"
          cmake --build . --target mill-pro --config Release

      - name: Archive Qt
        uses: actions/upload-artifact@v2
        with:
          name: mill-pro
          path: src/ui/qt/release/mill-pro.exe
